In [1]:
import polars as pl
from datetime import datetime

In [2]:
player_stats_raw = pl.read_csv("../csv/PlayerStatistics.csv")
player_stats_raw.schema

Schema([('firstName', String),
        ('lastName', String),
        ('personId', Int64),
        ('gameId', Int64),
        ('gameDate', String),
        ('playerteamCity', String),
        ('playerteamName', String),
        ('opponentteamCity', String),
        ('opponentteamName', String),
        ('gameType', String),
        ('gameLabel', String),
        ('gameSubLabel', String),
        ('seriesGameNumber', Float64),
        ('win', Int64),
        ('home', Int64),
        ('numMinutes', Float64),
        ('points', Float64),
        ('assists', Float64),
        ('blocks', Float64),
        ('steals', Float64),
        ('fieldGoalsAttempted', Float64),
        ('fieldGoalsMade', Float64),
        ('fieldGoalsPercentage', Float64),
        ('threePointersAttempted', Float64),
        ('threePointersMade', Float64),
        ('threePointersPercentage', Float64),
        ('freeThrowsAttempted', Float64),
        ('freeThrowsMade', Float64),
        ('freeThrowsPercentage', Float64),
        ('reboundsDefensive', Float64),
        ('reboundsOffensive', Float64),
        ('reboundsTotal', Float64),
        ('foulsPersonal', Float64),
        ('turnovers', Float64),
        ('plusMinusPoints', Float64),
        ('encodedTeam', Int64)])

In [3]:
# Step 1: Parse the string column into Datetime
box_score = player_stats_raw.with_columns(
    pl.col("gameDate").str.strptime(pl.Datetime, "%Y-%m-%d %H:%M:%S")
)

# Step 2: Filter rows where gameDate >= 1980-07-16
cutoff_date = datetime(1980, 7, 16)
box_score = box_score.filter(pl.col("gameDate") >= cutoff_date).filter(pl.col("gameType") == "Regular Season")
player_stats = box_score.drop(["gameId","playerteamName", "opponentteamCity", "opponentteamName", "gameType", "gameLabel", "gameSubLabel", "seriesGameNumber", "win", "home", "fieldGoalsPercentage", "threePointersPercentage","freeThrowsPercentage"])
player_stats

shape: (1_182_536, 23)
┌───────────┬───────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ firstName ┆ lastName  ┆ personId ┆ gameDate  ┆ … ┆ foulsPers ┆ turnovers ┆ plusMinus ┆ encodedTe │
│ ---       ┆ ---       ┆ ---      ┆ ---       ┆   ┆ onal      ┆ ---       ┆ Points    ┆ am        │
│ str       ┆ str       ┆ i64      ┆ datetime[ ┆   ┆ ---       ┆ f64       ┆ ---       ┆ ---       │
│           ┆           ┆          ┆ μs]       ┆   ┆ f64       ┆           ┆ f64       ┆ i64       │
╞═══════════╪═══════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ Jeff      ┆ Green     ┆ 201145   ┆ 2025-04-1 ┆ … ┆ 1.0       ┆ 0.0       ┆ -14.0     ┆ 11        │
│           ┆           ┆          ┆ 3         ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ 15:30:00  ┆   ┆           ┆           ┆           ┆           │
│ Russell   ┆ Westbrook ┆ 201566   ┆ 2025-04-1 ┆ … ┆ 1.0       ┆ 1.0       ┆ 8.0       ┆ 8         │
│           ┆           ┆          ┆ 3         ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ 15:30:00  ┆   ┆           ┆           ┆           ┆           │
│ DeAndre   ┆ Jordan    ┆ 201599   ┆ 2025-04-1 ┆ … ┆ 0.0       ┆ 0.0       ┆ -9.0      ┆ 8         │
│           ┆           ┆          ┆ 3         ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ 15:30:00  ┆   ┆           ┆           ┆           ┆           │
│ Steven    ┆ Adams     ┆ 203500   ┆ 2025-04-1 ┆ … ┆ 2.0       ┆ 1.0       ┆ -23.0     ┆ 11        │
│           ┆           ┆          ┆ 3         ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ 15:30:00  ┆   ┆           ┆           ┆           ┆           │
│ Aaron     ┆ Gordon    ┆ 203932   ┆ 2025-04-1 ┆ … ┆ 0.0       ┆ 3.0       ┆ 21.0      ┆ 8         │
│           ┆           ┆          ┆ 3         ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ 15:30:00  ┆   ┆           ┆           ┆           ┆           │
│ …         ┆ …         ┆ …        ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ Louis     ┆ Orr       ┆ 77770    ┆ 1980-10-1 ┆ … ┆ 1.0       ┆ 0.0       ┆ 0.0       ┆ 12        │
│           ┆           ┆          ┆ 0         ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ 20:00:00  ┆   ┆           ┆           ┆           ┆           │
│ Cliff T.  ┆ Robinson  ┆ 77986    ┆ 1980-10-1 ┆ … ┆ 3.0       ┆ 6.0       ┆ 0.0       ┆ 19        │
│           ┆           ┆          ┆ 0         ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ 20:00:00  ┆   ┆           ┆           ┆           ┆           │
│ Jerry     ┆ Sichting  ┆ 78146    ┆ 1980-10-1 ┆ … ┆ 1.0       ┆ 0.0       ┆ 0.0       ┆ 12        │
│           ┆           ┆          ┆ 0         ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ 20:00:00  ┆   ┆           ┆           ┆           ┆           │
│ Jan       ┆ Van Breda ┆ 78400    ┆ 1980-10-1 ┆ … ┆ 3.0       ┆ 0.0       ┆ 0.0       ┆ 19        │
│           ┆ Kolff     ┆          ┆ 0         ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ 20:00:00  ┆   ┆           ┆           ┆           ┆           │
│ Foots     ┆ Walker    ┆ 78436    ┆ 1980-10-1 ┆ … ┆ 2.0       ┆ 0.0       ┆ 0.0       ┆ 19        │
│           ┆           ┆          ┆ 0         ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ 20:00:00  ┆   ┆           ┆           ┆           ┆           │
└───────────┴───────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [4]:
player_stats = player_stats.with_columns(
    pl.when(pl.col("gameDate").dt.month() > 7)
      .then(pl.col("gameDate").dt.year())
      .otherwise(pl.col("gameDate").dt.year() - 1)
      .alias("season")
)
player_stats = player_stats.drop(["firstName", "lastName","gameDate"])
player_stats

shape: (1_182_536, 21)
┌──────────┬─────────────┬────────────┬────────┬───┬───────────┬─────────────┬────────────┬────────┐
│ personId ┆ playerteamC ┆ numMinutes ┆ points ┆ … ┆ turnovers ┆ plusMinusPo ┆ encodedTea ┆ season │
│ ---      ┆ ity         ┆ ---        ┆ ---    ┆   ┆ ---       ┆ ints        ┆ m          ┆ ---    │
│ i64      ┆ ---         ┆ f64        ┆ f64    ┆   ┆ f64       ┆ ---         ┆ ---        ┆ i32    │
│          ┆ str         ┆            ┆        ┆   ┆           ┆ f64         ┆ i64        ┆        │
╞══════════╪═════════════╪════════════╪════════╪═══╪═══════════╪═════════════╪════════════╪════════╡
│ 201145   ┆ Houston     ┆ 11.31      ┆ 5.0    ┆ … ┆ 0.0       ┆ -14.0       ┆ 11         ┆ 2024   │
│ 201566   ┆ Denver      ┆ 22.39      ┆ 17.0   ┆ … ┆ 1.0       ┆ 8.0         ┆ 8          ┆ 2024   │
│ 201599   ┆ Denver      ┆ 10.52      ┆ 4.0    ┆ … ┆ 0.0       ┆ -9.0        ┆ 8          ┆ 2024   │
│ 203500   ┆ Houston     ┆ 17.13      ┆ 4.0    ┆ … ┆ 1.0       ┆ -23.0       ┆ 11         ┆ 2024   │
│ 203932   ┆ Denver      ┆ 26.23      ┆ 18.0   ┆ … ┆ 3.0       ┆ 21.0        ┆ 8          ┆ 2024   │
│ …        ┆ …           ┆ …          ┆ …      ┆ … ┆ …         ┆ …           ┆ …          ┆ …      │
│ 77770    ┆ Indiana     ┆ 8.0        ┆ 4.0    ┆ … ┆ 0.0       ┆ 0.0         ┆ 12         ┆ 1980   │
│ 77986    ┆ New Jersey  ┆ 29.0       ┆ 11.0   ┆ … ┆ 6.0       ┆ 0.0         ┆ 19         ┆ 1980   │
│ 78146    ┆ Indiana     ┆ 10.0       ┆ 4.0    ┆ … ┆ 0.0       ┆ 0.0         ┆ 12         ┆ 1980   │
│ 78400    ┆ New Jersey  ┆ 20.0       ┆ 4.0    ┆ … ┆ 0.0       ┆ 0.0         ┆ 19         ┆ 1980   │
│ 78436    ┆ New Jersey  ┆ 31.0       ┆ 5.0    ┆ … ┆ 0.0       ┆ 0.0         ┆ 19         ┆ 1980   │
└──────────┴─────────────┴────────────┴────────┴───┴───────────┴─────────────┴────────────┴────────┘

In [5]:
# Get unique values and dense ranks
mapping_df = player_stats.select([
    pl.col("playerteamCity").unique().sort().alias("playerteamCity")
]).with_columns([
    pl.col("playerteamCity").rank("dense").cast(pl.Int64).alias("encodedTeam")
])

# Convert to a dictionary
mapping_dict = dict(zip(mapping_df["playerteamCity"].to_list(), mapping_df["encodedTeam"].to_list()))
print(mapping_dict)
player_stats = player_stats.with_columns(encodedTeam = pl.col("playerteamCity").rank("dense")).drop("playerteamCity")

{'Atlanta': 1, 'Boston': 2, 'Brooklyn': 3, 'Charlotte': 4, 'Chicago': 5, 'Cleveland': 6, 'Dallas': 7, 'Denver': 8, 'Detroit': 9, 'Golden State': 10, 'Houston': 11, 'Indiana': 12, 'Kansas City': 13, 'Los Angeles': 14, 'Memphis': 15, 'Miami': 16, 'Milwaukee': 17, 'Minnesota': 18, 'New Jersey': 19, 'New Orleans': 20, 'New York': 21, 'Oklahoma City': 22, 'Orlando': 23, 'Philadelphia': 24, 'Phoenix': 25, 'Portland': 26, 'Sacramento': 27, 'San Antonio': 28, 'San Diego': 29, 'Seattle': 30, 'Toronto': 31, 'Utah': 32, 'Vancouver': 33, 'Washington': 34}

In [6]:
player_stats

shape: (1_182_536, 20)
┌──────────┬────────────┬────────┬─────────┬───┬───────────┬────────────────┬─────────────┬────────┐
│ personId ┆ numMinutes ┆ points ┆ assists ┆ … ┆ turnovers ┆ plusMinusPoint ┆ encodedTeam ┆ season │
│ ---      ┆ ---        ┆ ---    ┆ ---     ┆   ┆ ---       ┆ s              ┆ ---         ┆ ---    │
│ i64      ┆ f64        ┆ f64    ┆ f64     ┆   ┆ f64       ┆ ---            ┆ u32         ┆ i32    │
│          ┆            ┆        ┆         ┆   ┆           ┆ f64            ┆             ┆        │
╞══════════╪════════════╪════════╪═════════╪═══╪═══════════╪════════════════╪═════════════╪════════╡
│ 201145   ┆ 11.31      ┆ 5.0    ┆ 0.0     ┆ … ┆ 0.0       ┆ -14.0          ┆ 11          ┆ 2024   │
│ 201566   ┆ 22.39      ┆ 17.0   ┆ 6.0     ┆ … ┆ 1.0       ┆ 8.0            ┆ 8           ┆ 2024   │
│ 201599   ┆ 10.52      ┆ 4.0    ┆ 0.0     ┆ … ┆ 0.0       ┆ -9.0           ┆ 8           ┆ 2024   │
│ 203500   ┆ 17.13      ┆ 4.0    ┆ 1.0     ┆ … ┆ 1.0       ┆ -23.0          ┆ 11          ┆ 2024   │
│ 203932   ┆ 26.23      ┆ 18.0   ┆ 3.0     ┆ … ┆ 3.0       ┆ 21.0           ┆ 8           ┆ 2024   │
│ …        ┆ …          ┆ …      ┆ …       ┆ … ┆ …         ┆ …              ┆ …           ┆ …      │
│ 77770    ┆ 8.0        ┆ 4.0    ┆ 0.0     ┆ … ┆ 0.0       ┆ 0.0            ┆ 12          ┆ 1980   │
│ 77986    ┆ 29.0       ┆ 11.0   ┆ 3.0     ┆ … ┆ 6.0       ┆ 0.0            ┆ 19          ┆ 1980   │
│ 78146    ┆ 10.0       ┆ 4.0    ┆ 3.0     ┆ … ┆ 0.0       ┆ 0.0            ┆ 12          ┆ 1980   │
│ 78400    ┆ 20.0       ┆ 4.0    ┆ 0.0     ┆ … ┆ 0.0       ┆ 0.0            ┆ 19          ┆ 1980   │
│ 78436    ┆ 31.0       ┆ 5.0    ┆ 7.0     ┆ … ┆ 0.0       ┆ 0.0            ┆ 19          ┆ 1980   │
└──────────┴────────────┴────────┴─────────┴───┴───────────┴────────────────┴─────────────┴────────┘

In [7]:
per_game = player_stats.group_by(["personId", "season", "encodedTeam"]).mean().drop(["reboundsDefensive", "reboundsOffensive", "foulsPersonal", "plusMinusPoints"])

In [8]:
per_game

shape: (22_459, 16)
┌──────────┬────────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ personId ┆ season ┆ encodedTea ┆ numMinutes ┆ … ┆ freeThrows ┆ freeThrow ┆ reboundsT ┆ turnovers │
│ ---      ┆ ---    ┆ m          ┆ ---        ┆   ┆ Attempted  ┆ sMade     ┆ otal      ┆ ---       │
│ i64      ┆ i32    ┆ ---        ┆ f64        ┆   ┆ ---        ┆ ---       ┆ ---       ┆ f64       │
│          ┆        ┆ u32        ┆            ┆   ┆ f64        ┆ f64       ┆ f64       ┆           │
╞══════════╪════════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2555     ┆ 2015   ┆ 22         ┆ 11.322034  ┆ … ┆ 0.402439   ┆ 0.280488  ┆ 2.085366  ┆ 0.609756  │
│ 201160   ┆ 2007   ┆ 24         ┆ 14.078947  ┆ … ┆ 1.037975   ┆ 0.683544  ┆ 2.911392  ┆ 0.607595  │
│ 781      ┆ 2000   ┆ 26         ┆ 3.769231   ┆ … ┆ 0.067797   ┆ 0.033898  ┆ 0.305085  ┆ 0.0       │
│ 1628385  ┆ 2019   ┆ 27         ┆ 14.461538  ┆ … ┆ 0.754386   ┆ 0.578947  ┆ 2.807018  ┆ 0.614035  │
│ 2410     ┆ 2003   ┆ 12         ┆ 17.950617  ┆ … ┆ 1.817073   ┆ 1.512195  ┆ 1.536585  ┆ 0.890244  │
│ …        ┆ …      ┆ …          ┆ …          ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 201595   ┆ 2009   ┆ 27         ┆ 6.125      ┆ … ┆ 0.769231   ┆ 0.307692  ┆ 1.384615  ┆ 0.153846  │
│ 76441    ┆ 1989   ┆ 26         ┆ 14.886076  ┆ … ┆ 0.493671   ┆ 0.316456  ┆ 4.291139  ┆ 0.493671  │
│ 1626246  ┆ 2021   ┆ 7          ┆ 5.130435   ┆ … ┆ 0.289474   ┆ 0.171053  ┆ 0.513158  ┆ 0.197368  │
│ 202721   ┆ 2013   ┆ 14         ┆ 5.0        ┆ … ┆ 0.2        ┆ 0.1       ┆ 0.5       ┆ 0.2       │
│ 698      ┆ 1996   ┆ 8          ┆ null       ┆ … ┆ 0.0        ┆ 0.0       ┆ 0.0       ┆ 0.0       │
└──────────┴────────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [9]:
player_stats

shape: (1_182_536, 20)
┌──────────┬────────────┬────────┬─────────┬───┬───────────┬────────────────┬─────────────┬────────┐
│ personId ┆ numMinutes ┆ points ┆ assists ┆ … ┆ turnovers ┆ plusMinusPoint ┆ encodedTeam ┆ season │
│ ---      ┆ ---        ┆ ---    ┆ ---     ┆   ┆ ---       ┆ s              ┆ ---         ┆ ---    │
│ i64      ┆ f64        ┆ f64    ┆ f64     ┆   ┆ f64       ┆ ---            ┆ u32         ┆ i32    │
│          ┆            ┆        ┆         ┆   ┆           ┆ f64            ┆             ┆        │
╞══════════╪════════════╪════════╪═════════╪═══╪═══════════╪════════════════╪═════════════╪════════╡
│ 201145   ┆ 11.31      ┆ 5.0    ┆ 0.0     ┆ … ┆ 0.0       ┆ -14.0          ┆ 11          ┆ 2024   │
│ 201566   ┆ 22.39      ┆ 17.0   ┆ 6.0     ┆ … ┆ 1.0       ┆ 8.0            ┆ 8           ┆ 2024   │
│ 201599   ┆ 10.52      ┆ 4.0    ┆ 0.0     ┆ … ┆ 0.0       ┆ -9.0           ┆ 8           ┆ 2024   │
│ 203500   ┆ 17.13      ┆ 4.0    ┆ 1.0     ┆ … ┆ 1.0       ┆ -23.0          ┆ 11          ┆ 2024   │
│ 203932   ┆ 26.23      ┆ 18.0   ┆ 3.0     ┆ … ┆ 3.0       ┆ 21.0           ┆ 8           ┆ 2024   │
│ …        ┆ …          ┆ …      ┆ …       ┆ … ┆ …         ┆ …              ┆ …           ┆ …      │
│ 77770    ┆ 8.0        ┆ 4.0    ┆ 0.0     ┆ … ┆ 0.0       ┆ 0.0            ┆ 12          ┆ 1980   │
│ 77986    ┆ 29.0       ┆ 11.0   ┆ 3.0     ┆ … ┆ 6.0       ┆ 0.0            ┆ 19          ┆ 1980   │
│ 78146    ┆ 10.0       ┆ 4.0    ┆ 3.0     ┆ … ┆ 0.0       ┆ 0.0            ┆ 12          ┆ 1980   │
│ 78400    ┆ 20.0       ┆ 4.0    ┆ 0.0     ┆ … ┆ 0.0       ┆ 0.0            ┆ 19          ┆ 1980   │
│ 78436    ┆ 31.0       ┆ 5.0    ┆ 7.0     ┆ … ┆ 0.0       ┆ 0.0            ┆ 19          ┆ 1980   │
└──────────┴────────────┴────────┴─────────┴───┴───────────┴────────────────┴─────────────┴────────┘

In [10]:
per_game.write_csv("../csv/PerGame.csv")

In [11]:
games = pl.read_csv("../csv/Games.csv")
games

shape: (71_879, 17)
┌──────────┬────────────┬────────────┬───────────┬───┬─────────┬───────────┬───────────┬───────────┐
│ gameId   ┆ gameDate   ┆ hometeamCi ┆ hometeamN ┆ … ┆ arenaId ┆ gameLabel ┆ gameSubLa ┆ seriesGam │
│ ---      ┆ ---        ┆ ty         ┆ ame       ┆   ┆ ---     ┆ ---       ┆ bel       ┆ eNumber   │
│ i64      ┆ str        ┆ ---        ┆ ---       ┆   ┆ i64     ┆ str       ┆ ---       ┆ ---       │
│          ┆            ┆ str        ┆ str       ┆   ┆         ┆           ┆ str       ┆ f64       │
╞══════════╪════════════╪════════════╪═══════════╪═══╪═════════╪═══════════╪═══════════╪═══════════╡
│ 42400407 ┆ 2025-06-22 ┆ Oklahoma   ┆ Thunder   ┆ … ┆ 1000052 ┆ NBA       ┆ Game 7    ┆ 7.0       │
│          ┆ 20:00:00   ┆ City       ┆           ┆   ┆         ┆ Finals    ┆           ┆           │
│ 42400406 ┆ 2025-06-19 ┆ Indiana    ┆ Pacers    ┆ … ┆ 1000063 ┆ NBA       ┆ Game 6    ┆ 6.0       │
│          ┆ 20:30:00   ┆            ┆           ┆   ┆         ┆ Finals    ┆           ┆           │
│ 42400405 ┆ 2025-06-16 ┆ Oklahoma   ┆ Thunder   ┆ … ┆ 1000052 ┆ NBA       ┆ Game 5    ┆ 5.0       │
│          ┆ 20:30:00   ┆ City       ┆           ┆   ┆         ┆ Finals    ┆           ┆           │
│ 42400404 ┆ 2025-06-13 ┆ Indiana    ┆ Pacers    ┆ … ┆ 1000063 ┆ NBA       ┆ Game 4    ┆ 4.0       │
│          ┆ 20:30:00   ┆            ┆           ┆   ┆         ┆ Finals    ┆           ┆           │
│ 42400403 ┆ 2025-06-11 ┆ Indiana    ┆ Pacers    ┆ … ┆ 1000063 ┆ NBA       ┆ Game 3    ┆ 3.0       │
│          ┆ 20:30:00   ┆            ┆           ┆   ┆         ┆ Finals    ┆           ┆           │
│ …        ┆ …          ┆ …          ┆ …         ┆ … ┆ …       ┆ …         ┆ …         ┆ …         │
│ 24600083 ┆ 1946-12-08 ┆ New York   ┆ Knicks    ┆ … ┆ 0       ┆ null      ┆ null      ┆ null      │
│          ┆ 19:00:00   ┆            ┆           ┆   ┆         ┆           ┆           ┆           │
│ 24600078 ┆ 1946-12-07 ┆ Boston     ┆ Celtics   ┆ … ┆ 0       ┆ null      ┆ null      ┆ null      │
│          ┆ 19:00:00   ┆            ┆           ┆   ┆         ┆           ┆           ┆           │
│ 24600076 ┆ 1946-12-05 ┆ Philadelph ┆ Warriors  ┆ … ┆ 0       ┆ null      ┆ null      ┆ null      │
│          ┆ 19:00:00   ┆ ia         ┆           ┆   ┆         ┆           ┆           ┆           │
│ 24600063 ┆ 1946-11-30 ┆ New York   ┆ Knicks    ┆ … ┆ 0       ┆ null      ┆ null      ┆ null      │
│          ┆ 19:00:00   ┆            ┆           ┆   ┆         ┆           ┆           ┆           │
│ 24600052 ┆ 1946-11-26 ┆ Philadelph ┆ Warriors  ┆ … ┆ 0       ┆ null      ┆ null      ┆ null      │
│          ┆ 19:00:00   ┆ ia         ┆           ┆   ┆         ┆           ┆           ┆           │
└──────────┴────────────┴────────────┴───────────┴───┴─────────┴───────────┴───────────┴───────────┘

In [12]:
games = games.with_columns(
    pl.col("hometeamCity").map_elements(lambda x: mapping_dict.get(x, -1), return_dtype=pl.Int64).alias("encodedHomeTeam")
)

games = games.with_columns(
    pl.col("awayteamCity").map_elements(lambda x: mapping_dict.get(x, -1), return_dtype=pl.Int64).alias("encodedAwayTeam")
)

games

shape: (71_879, 19)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ gameId   ┆ gameDate  ┆ hometeamC ┆ hometeamN ┆ … ┆ gameSubLa ┆ seriesGam ┆ encodedHo ┆ encodedAw │
│ ---      ┆ ---       ┆ ity       ┆ ame       ┆   ┆ bel       ┆ eNumber   ┆ meTeam    ┆ ayTeam    │
│ i64      ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│          ┆           ┆ str       ┆ str       ┆   ┆ str       ┆ f64       ┆ i64       ┆ i64       │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 42400407 ┆ 2025-06-2 ┆ Oklahoma  ┆ Thunder   ┆ … ┆ Game 7    ┆ 7.0       ┆ 22        ┆ 12        │
│          ┆ 2         ┆ City      ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 20:00:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 42400406 ┆ 2025-06-1 ┆ Indiana   ┆ Pacers    ┆ … ┆ Game 6    ┆ 6.0       ┆ 12        ┆ 22        │
│          ┆ 9         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 20:30:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 42400405 ┆ 2025-06-1 ┆ Oklahoma  ┆ Thunder   ┆ … ┆ Game 5    ┆ 5.0       ┆ 22        ┆ 12        │
│          ┆ 6         ┆ City      ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 20:30:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 42400404 ┆ 2025-06-1 ┆ Indiana   ┆ Pacers    ┆ … ┆ Game 4    ┆ 4.0       ┆ 12        ┆ 22        │
│          ┆ 3         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 20:30:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 42400403 ┆ 2025-06-1 ┆ Indiana   ┆ Pacers    ┆ … ┆ Game 3    ┆ 3.0       ┆ 12        ┆ 22        │
│          ┆ 1         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 20:30:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ …        ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 24600083 ┆ 1946-12-0 ┆ New York  ┆ Knicks    ┆ … ┆ null      ┆ null      ┆ 21        ┆ 2         │
│          ┆ 8         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 19:00:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 24600078 ┆ 1946-12-0 ┆ Boston    ┆ Celtics   ┆ … ┆ null      ┆ null      ┆ 2         ┆ 21        │
│          ┆ 7         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 19:00:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 24600076 ┆ 1946-12-0 ┆ Philadelp ┆ Warriors  ┆ … ┆ null      ┆ null      ┆ 24        ┆ 21        │
│          ┆ 5         ┆ hia       ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 19:00:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 24600063 ┆ 1946-11-3 ┆ New York  ┆ Knicks    ┆ … ┆ null      ┆ null      ┆ 21        ┆ 24        │
│          ┆ 0         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 19:00:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 24600052 ┆ 1946-11-2 ┆ Philadelp ┆ Warriors  ┆ … ┆ null      ┆ null      ┆ 24        ┆ 2         │
│          ┆ 6         ┆ hia       ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 19:00:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [13]:
# Step 1: Parse the string column into Datetime
games = games.with_columns(
    pl.col("gameDate").str.strptime(pl.Datetime, "%Y-%m-%d %H:%M:%S")
)

# Step 2: Filter rows where gameDate >= 1980-07-16
cutoff_date = datetime(1980, 7, 16)
games = games.filter(pl.col("gameDate") >= cutoff_date).filter(pl.col("gameType") == "Regular Season").drop(["hometeamCity", "hometeamName", "hometeamId", "awayteamCity", "awayteamName", "awayteamId", "winner", "gameType", "attendance","arenaId", "gameLabel", "gameSubLabel", "seriesGameNumber"])
games

shape: (50_646, 6)
┌──────────┬─────────────────────┬───────────┬───────────┬─────────────────┬─────────────────┐
│ gameId   ┆ gameDate            ┆ homeScore ┆ awayScore ┆ encodedHomeTeam ┆ encodedAwayTeam │
│ ---      ┆ ---                 ┆ ---       ┆ ---       ┆ ---             ┆ ---             │
│ i64      ┆ datetime[μs]        ┆ i64       ┆ i64       ┆ i64             ┆ i64             │
╞══════════╪═════════════════════╪═══════════╪═══════════╪═════════════════╪═════════════════╡
│ 22401193 ┆ 2025-04-13 15:30:00 ┆ 111       ┆ 126       ┆ 11              ┆ 8               │
│ 22401194 ┆ 2025-04-13 15:30:00 ┆ 132       ┆ 97        ┆ 15              ┆ 7               │
│ 22401195 ┆ 2025-04-13 15:30:00 ┆ 116       ┆ 105       ┆ 18              ┆ 32              │
│ 22401196 ┆ 2025-04-13 15:30:00 ┆ 100       ┆ 115       ┆ 20              ┆ 22              │
│ 22401197 ┆ 2025-04-13 15:30:00 ┆ 125       ┆ 118       ┆ 28              ┆ 31              │
│ …        ┆ …                   ┆ …         ┆ …         ┆ …               ┆ …               │
│ 28000005 ┆ 1980-10-10 20:00:00 ┆ 85        ┆ 95        ┆ 9               ┆ 34              │
│ 28000006 ┆ 1980-10-10 20:00:00 ┆ 98        ┆ 99        ┆ 30              ┆ 14              │
│ 28000007 ┆ 1980-10-10 20:00:00 ┆ 130       ┆ 103       ┆ 2               ┆ 6               │
│ 28000008 ┆ 1980-10-10 20:00:00 ┆ 96        ┆ 86        ┆ 32              ┆ 26              │
│ 28000009 ┆ 1980-10-10 20:00:00 ┆ 91        ┆ 110       ┆ 19              ┆ 12              │
└──────────┴─────────────────────┴───────────┴───────────┴─────────────────┴─────────────────┘

In [14]:
games = games.with_columns(
    pl.when(pl.col("gameDate").dt.month() > 7)
      .then(pl.col("gameDate").dt.year())
      .otherwise(pl.col("gameDate").dt.year() - 1)
      .alias("season")
).drop("gameDate")

games

shape: (50_646, 6)
┌──────────┬───────────┬───────────┬─────────────────┬─────────────────┬────────┐
│ gameId   ┆ homeScore ┆ awayScore ┆ encodedHomeTeam ┆ encodedAwayTeam ┆ season │
│ ---      ┆ ---       ┆ ---       ┆ ---             ┆ ---             ┆ ---    │
│ i64      ┆ i64       ┆ i64       ┆ i64             ┆ i64             ┆ i32    │
╞══════════╪═══════════╪═══════════╪═════════════════╪═════════════════╪════════╡
│ 22401193 ┆ 111       ┆ 126       ┆ 11              ┆ 8               ┆ 2024   │
│ 22401194 ┆ 132       ┆ 97        ┆ 15              ┆ 7               ┆ 2024   │
│ 22401195 ┆ 116       ┆ 105       ┆ 18              ┆ 32              ┆ 2024   │
│ 22401196 ┆ 100       ┆ 115       ┆ 20              ┆ 22              ┆ 2024   │
│ 22401197 ┆ 125       ┆ 118       ┆ 28              ┆ 31              ┆ 2024   │
│ …        ┆ …         ┆ …         ┆ …               ┆ …               ┆ …      │
│ 28000005 ┆ 85        ┆ 95        ┆ 9               ┆ 34              ┆ 1980   │
│ 28000006 ┆ 98        ┆ 99        ┆ 30              ┆ 14              ┆ 1980   │
│ 28000007 ┆ 130       ┆ 103       ┆ 2               ┆ 6               ┆ 1980   │
│ 28000008 ┆ 96        ┆ 86        ┆ 32              ┆ 26              ┆ 1980   │
│ 28000009 ┆ 91        ┆ 110       ┆ 19              ┆ 12              ┆ 1980   │
└──────────┴───────────┴───────────┴─────────────────┴─────────────────┴────────┘

In [15]:
per_game

shape: (22_459, 16)
┌──────────┬────────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ personId ┆ season ┆ encodedTea ┆ numMinutes ┆ … ┆ freeThrows ┆ freeThrow ┆ reboundsT ┆ turnovers │
│ ---      ┆ ---    ┆ m          ┆ ---        ┆   ┆ Attempted  ┆ sMade     ┆ otal      ┆ ---       │
│ i64      ┆ i32    ┆ ---        ┆ f64        ┆   ┆ ---        ┆ ---       ┆ ---       ┆ f64       │
│          ┆        ┆ u32        ┆            ┆   ┆ f64        ┆ f64       ┆ f64       ┆           │
╞══════════╪════════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2555     ┆ 2015   ┆ 22         ┆ 11.322034  ┆ … ┆ 0.402439   ┆ 0.280488  ┆ 2.085366  ┆ 0.609756  │
│ 201160   ┆ 2007   ┆ 24         ┆ 14.078947  ┆ … ┆ 1.037975   ┆ 0.683544  ┆ 2.911392  ┆ 0.607595  │
│ 781      ┆ 2000   ┆ 26         ┆ 3.769231   ┆ … ┆ 0.067797   ┆ 0.033898  ┆ 0.305085  ┆ 0.0       │
│ 1628385  ┆ 2019   ┆ 27         ┆ 14.461538  ┆ … ┆ 0.754386   ┆ 0.578947  ┆ 2.807018  ┆ 0.614035  │
│ 2410     ┆ 2003   ┆ 12         ┆ 17.950617  ┆ … ┆ 1.817073   ┆ 1.512195  ┆ 1.536585  ┆ 0.890244  │
│ …        ┆ …      ┆ …          ┆ …          ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 201595   ┆ 2009   ┆ 27         ┆ 6.125      ┆ … ┆ 0.769231   ┆ 0.307692  ┆ 1.384615  ┆ 0.153846  │
│ 76441    ┆ 1989   ┆ 26         ┆ 14.886076  ┆ … ┆ 0.493671   ┆ 0.316456  ┆ 4.291139  ┆ 0.493671  │
│ 1626246  ┆ 2021   ┆ 7          ┆ 5.130435   ┆ … ┆ 0.289474   ┆ 0.171053  ┆ 0.513158  ┆ 0.197368  │
│ 202721   ┆ 2013   ┆ 14         ┆ 5.0        ┆ … ┆ 0.2        ┆ 0.1       ┆ 0.5       ┆ 0.2       │
│ 698      ┆ 1996   ┆ 8          ┆ null       ┆ … ┆ 0.0        ┆ 0.0       ┆ 0.0       ┆ 0.0       │
└──────────┴────────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [16]:
# box_score = box_score.drop(["playerteamCity", "playerteamName",	"opponentteamCity",	"opponentteamName",	"gameType",	"gameLabel","gameSubLabel",	"seriesGameNumber", "win", "home", "fieldGoalsPercentage", "threePointersPercentage", "freeThrowsPercentage", "reboundsDefensive", "reboundsOffensive", "foulsPersonal", "plusMinusPoints"])
box_score = box_score.drop([	"gameType",	"gameLabel","gameSubLabel",	"seriesGameNumber", "win", "home", "fieldGoalsPercentage", "threePointersPercentage", "freeThrowsPercentage", "reboundsDefensive", "reboundsOffensive", "foulsPersonal", "plusMinusPoints"])
box_score = box_score.with_columns(
    pl.when(pl.col("gameDate").dt.month() > 7)
      .then(pl.col("gameDate").dt.year())
      .otherwise(pl.col("gameDate").dt.year() - 1)
      .alias("season")
).drop("gameDate")

In [17]:
box_score

shape: (1_182_536, 23)
┌───────────┬─────────────┬──────────┬──────────┬───┬────────────┬───────────┬────────────┬────────┐
│ firstName ┆ lastName    ┆ personId ┆ gameId   ┆ … ┆ reboundsTo ┆ turnovers ┆ encodedTea ┆ season │
│ ---       ┆ ---         ┆ ---      ┆ ---      ┆   ┆ tal        ┆ ---       ┆ m          ┆ ---    │
│ str       ┆ str         ┆ i64      ┆ i64      ┆   ┆ ---        ┆ f64       ┆ ---        ┆ i32    │
│           ┆             ┆          ┆          ┆   ┆ f64        ┆           ┆ i64        ┆        │
╞═══════════╪═════════════╪══════════╪══════════╪═══╪════════════╪═══════════╪════════════╪════════╡
│ Jeff      ┆ Green       ┆ 201145   ┆ 22401193 ┆ … ┆ 3.0        ┆ 0.0       ┆ 11         ┆ 2024   │
│ Russell   ┆ Westbrook   ┆ 201566   ┆ 22401193 ┆ … ┆ 0.0        ┆ 1.0       ┆ 8          ┆ 2024   │
│ DeAndre   ┆ Jordan      ┆ 201599   ┆ 22401193 ┆ … ┆ 5.0        ┆ 0.0       ┆ 8          ┆ 2024   │
│ Steven    ┆ Adams       ┆ 203500   ┆ 22401193 ┆ … ┆ 6.0        ┆ 1.0       ┆ 11         ┆ 2024   │
│ Aaron     ┆ Gordon      ┆ 203932   ┆ 22401193 ┆ … ┆ 7.0        ┆ 3.0       ┆ 8          ┆ 2024   │
│ …         ┆ …           ┆ …        ┆ …        ┆ … ┆ …          ┆ …         ┆ …          ┆ …      │
│ Louis     ┆ Orr         ┆ 77770    ┆ 28000009 ┆ … ┆ 2.0        ┆ 0.0       ┆ 12         ┆ 1980   │
│ Cliff T.  ┆ Robinson    ┆ 77986    ┆ 28000009 ┆ … ┆ 9.0        ┆ 6.0       ┆ 19         ┆ 1980   │
│ Jerry     ┆ Sichting    ┆ 78146    ┆ 28000009 ┆ … ┆ 0.0        ┆ 0.0       ┆ 12         ┆ 1980   │
│ Jan       ┆ Van Breda   ┆ 78400    ┆ 28000009 ┆ … ┆ 4.0        ┆ 0.0       ┆ 19         ┆ 1980   │
│           ┆ Kolff       ┆          ┆          ┆   ┆            ┆           ┆            ┆        │
│ Foots     ┆ Walker      ┆ 78436    ┆ 28000009 ┆ … ┆ 2.0        ┆ 0.0       ┆ 19         ┆ 1980   │
└───────────┴─────────────┴──────────┴──────────┴───┴────────────┴───────────┴────────────┴────────┘

In [18]:
box_score_with_per_game = box_score.join(per_game, on=["personId", "season"], how="left", suffix="pg")
box_score_with_per_game

shape: (1_328_190, 37)
┌───────────┬────────────┬──────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ firstName ┆ lastName   ┆ personId ┆ gameId   ┆ … ┆ freeThrow ┆ freeThrow ┆ reboundsT ┆ turnovers │
│ ---       ┆ ---        ┆ ---      ┆ ---      ┆   ┆ sAttempte ┆ sMadepg   ┆ otalpg    ┆ pg        │
│ str       ┆ str        ┆ i64      ┆ i64      ┆   ┆ dpg       ┆ ---       ┆ ---       ┆ ---       │
│           ┆            ┆          ┆          ┆   ┆ ---       ┆ f64       ┆ f64       ┆ f64       │
│           ┆            ┆          ┆          ┆   ┆ f64       ┆           ┆           ┆           │
╞═══════════╪════════════╪══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ Jeff      ┆ Green      ┆ 201145   ┆ 22401193 ┆ … ┆ 0.320988  ┆ 0.259259  ┆ 0.716049  ┆ 0.111111  │
│ Russell   ┆ Westbrook  ┆ 201566   ┆ 22401193 ┆ … ┆ 3.106667  ┆ 2.053333  ┆ 4.933333  ┆ 3.226667  │
│ DeAndre   ┆ Jordan     ┆ 201599   ┆ 22401193 ┆ … ┆ 0.780488  ┆ 0.329268  ┆ 3.463415  ┆ 0.487805  │
│ Steven    ┆ Adams      ┆ 203500   ┆ 22401193 ┆ … ┆ 1.328571  ┆ 0.614286  ┆ 4.671429  ┆ 0.771429  │
│ Aaron     ┆ Gordon     ┆ 203932   ┆ 22401193 ┆ … ┆ 3.509804  ┆ 2.843137  ┆ 4.843137  ┆ 1.431373  │
│ …         ┆ …          ┆ …        ┆ …        ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ Louis     ┆ Orr        ┆ 77770    ┆ 28000009 ┆ … ┆ 2.463415  ┆ 1.987805  ┆ 4.402439  ┆ 0.756098  │
│ Cliff T.  ┆ Robinson   ┆ 77986    ┆ 28000009 ┆ … ┆ 3.936508  ┆ 2.825397  ┆ 7.603175  ┆ 1.31746   │
│ Jerry     ┆ Sichting   ┆ 78146    ┆ 28000009 ┆ … ┆ 0.680851  ┆ 0.531915  ┆ 0.914894  ┆ 0.191489  │
│ Jan       ┆ Van Breda  ┆ 78400    ┆ 28000009 ┆ … ┆ 1.5       ┆ 1.25641   ┆ 2.589744  ┆ 0.5       │
│           ┆ Kolff      ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ Foots     ┆ Walker     ┆ 78436    ┆ 28000009 ┆ … ┆ 2.707317  ┆ 2.146341  ┆ 2.487805  ┆ 0.731707  │
└───────────┴────────────┴──────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [19]:
# pivot_df = box_score_with_per_game.pivot(
# values=[
#         "numMinutespg", "pointspg", "assistspg", "blockspg", "stealspg",
#         "fieldGoalsAttemptedpg", "fieldGoalsMadepg", "threePointersAttemptedpg",
#         "threePointersMadepg", "freeThrowsAttemptedpg", "freeThrowsMadepg",
#         "reboundsDefensive", "reboundsOffensive", "reboundsTotalpg",
#         "foulsPersonal", "turnoverspg", "plusMinusPoints"
#     ],    
#     index="gameId",
#     on="personId",
#     aggregate_function="first"             # assuming one stat row per game/player
# )

# pivot_df

In [20]:
master = games.join(box_score_with_per_game, on=["gameId", "season"], how="left")
master

shape: (1_328_192, 41)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ gameId   ┆ homeScore ┆ awayScore ┆ encodedHo ┆ … ┆ freeThrow ┆ freeThrow ┆ reboundsT ┆ turnovers │
│ ---      ┆ ---       ┆ ---       ┆ meTeam    ┆   ┆ sAttempte ┆ sMadepg   ┆ otalpg    ┆ pg        │
│ i64      ┆ i64       ┆ i64       ┆ ---       ┆   ┆ dpg       ┆ ---       ┆ ---       ┆ ---       │
│          ┆           ┆           ┆ i64       ┆   ┆ ---       ┆ f64       ┆ f64       ┆ f64       │
│          ┆           ┆           ┆           ┆   ┆ f64       ┆           ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 22401193 ┆ 111       ┆ 126       ┆ 11        ┆ … ┆ 0.320988  ┆ 0.259259  ┆ 0.716049  ┆ 0.111111  │
│ 22401193 ┆ 111       ┆ 126       ┆ 11        ┆ … ┆ 3.106667  ┆ 2.053333  ┆ 4.933333  ┆ 3.226667  │
│ 22401193 ┆ 111       ┆ 126       ┆ 11        ┆ … ┆ 0.780488  ┆ 0.329268  ┆ 3.463415  ┆ 0.487805  │
│ 22401193 ┆ 111       ┆ 126       ┆ 11        ┆ … ┆ 1.328571  ┆ 0.614286  ┆ 4.671429  ┆ 0.771429  │
│ 22401193 ┆ 111       ┆ 126       ┆ 11        ┆ … ┆ 3.509804  ┆ 2.843137  ┆ 4.843137  ┆ 1.431373  │
│ …        ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 28000009 ┆ 91        ┆ 110       ┆ 19        ┆ … ┆ 2.463415  ┆ 1.987805  ┆ 4.402439  ┆ 0.756098  │
│ 28000009 ┆ 91        ┆ 110       ┆ 19        ┆ … ┆ 3.936508  ┆ 2.825397  ┆ 7.603175  ┆ 1.31746   │
│ 28000009 ┆ 91        ┆ 110       ┆ 19        ┆ … ┆ 0.680851  ┆ 0.531915  ┆ 0.914894  ┆ 0.191489  │
│ 28000009 ┆ 91        ┆ 110       ┆ 19        ┆ … ┆ 1.5       ┆ 1.25641   ┆ 2.589744  ┆ 0.5       │
│ 28000009 ┆ 91        ┆ 110       ┆ 19        ┆ … ┆ 2.707317  ┆ 2.146341  ┆ 2.487805  ┆ 0.731707  │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [21]:
unique_game_ids = games.select(pl.col("gameId").unique()).sort(by="gameId")
unique_game_ids

shape: (50_646, 1)
┌──────────┐
│ gameId   │
│ ---      │
│ i64      │
╞══════════╡
│ 20000001 │
│ 20000002 │
│ 20000003 │
│ 20000004 │
│ 20000005 │
│ …        │
│ 29901186 │
│ 29901187 │
│ 29901188 │
│ 29901189 │
│ 62400001 │
└──────────┘

In [22]:
games

shape: (50_646, 6)
┌──────────┬───────────┬───────────┬─────────────────┬─────────────────┬────────┐
│ gameId   ┆ homeScore ┆ awayScore ┆ encodedHomeTeam ┆ encodedAwayTeam ┆ season │
│ ---      ┆ ---       ┆ ---       ┆ ---             ┆ ---             ┆ ---    │
│ i64      ┆ i64       ┆ i64       ┆ i64             ┆ i64             ┆ i32    │
╞══════════╪═══════════╪═══════════╪═════════════════╪═════════════════╪════════╡
│ 22401193 ┆ 111       ┆ 126       ┆ 11              ┆ 8               ┆ 2024   │
│ 22401194 ┆ 132       ┆ 97        ┆ 15              ┆ 7               ┆ 2024   │
│ 22401195 ┆ 116       ┆ 105       ┆ 18              ┆ 32              ┆ 2024   │
│ 22401196 ┆ 100       ┆ 115       ┆ 20              ┆ 22              ┆ 2024   │
│ 22401197 ┆ 125       ┆ 118       ┆ 28              ┆ 31              ┆ 2024   │
│ …        ┆ …         ┆ …         ┆ …               ┆ …               ┆ …      │
│ 28000005 ┆ 85        ┆ 95        ┆ 9               ┆ 34              ┆ 1980   │
│ 28000006 ┆ 98        ┆ 99        ┆ 30              ┆ 14              ┆ 1980   │
│ 28000007 ┆ 130       ┆ 103       ┆ 2               ┆ 6               ┆ 1980   │
│ 28000008 ┆ 96        ┆ 86        ┆ 32              ┆ 26              ┆ 1980   │
│ 28000009 ┆ 91        ┆ 110       ┆ 19              ┆ 12              ┆ 1980   │
└──────────┴───────────┴───────────┴─────────────────┴─────────────────┴────────┘

In [23]:

new_columns = [
    "numMinutes",
    "points",
    "assists",
    "blocks",
    "steals",
    "reboundsTotal",
    "turnovers",
]


cols = []

for teamIdx in range(2):
    teamStr = 't' + str(teamIdx)
    for playerIdx in range(15):
        playerStr = 'p' + str(playerIdx)
        prefix = teamStr + '_' + playerStr + '_'
        for col in new_columns:
            cols.append(prefix + col)
        
print(cols)
master = games.with_columns([
    pl.lit(0).alias(col_name) for col_name in cols
])
new_columns = [
    "numMinutespg",
    "pointspg",
    "assistspg",
    "blockspg",
    "stealspg",
    "fieldGoalsAttemptedpg",
    "fieldGoalsMadepg",
    "threePointersAttemptedpg",
    "threePointersMadepg",
    "freeThrowsAttemptedpg",
    "freeThrowsMadepg",
    "reboundsTotalpg",
    "turnoverspg",
]
cols = []

for teamIdx in range(2):
    teamStr = 't' + str(teamIdx)
    for playerIdx in range(15):
        playerStr = 'p' + str(playerIdx)
        prefix = teamStr + '_' + playerStr + '_'
        for col in new_columns:
            cols.append(prefix + col)
        
print(cols)
master = master.with_columns([
    pl.lit(0).alias(col_name) for col_name in cols
])

master

['t0_p0_numMinutes', 't0_p0_points', 't0_p0_assists', 't0_p0_blocks', 't0_p0_steals', 't0_p0_reboundsTotal', 't0_p0_turnovers', 't0_p1_numMinutes', 't0_p1_points', 't0_p1_assists', 't0_p1_blocks', 't0_p1_steals', 't0_p1_reboundsTotal', 't0_p1_turnovers', 't0_p2_numMinutes', 't0_p2_points', 't0_p2_assists', 't0_p2_blocks', 't0_p2_steals', 't0_p2_reboundsTotal', 't0_p2_turnovers', 't0_p3_numMinutes', 't0_p3_points', 't0_p3_assists', 't0_p3_blocks', 't0_p3_steals', 't0_p3_reboundsTotal', 't0_p3_turnovers', 't0_p4_numMinutes', 't0_p4_points', 't0_p4_assists', 't0_p4_blocks', 't0_p4_steals', 't0_p4_reboundsTotal', 't0_p4_turnovers', 't0_p5_numMinutes', 't0_p5_points', 't0_p5_assists', 't0_p5_blocks', 't0_p5_steals', 't0_p5_reboundsTotal', 't0_p5_turnovers', 't0_p6_numMinutes', 't0_p6_points', 't0_p6_assists', 't0_p6_blocks', 't0_p6_steals', 't0_p6_reboundsTotal', 't0_p6_turnovers', 't0_p7_numMinutes', 't0_p7_points', 't0_p7_assists', 't0_p7_blocks', 't0_p7_steals', 't0_p7_reboundsTotal', 't0_p7_turnovers', 't0_p8_numMinutes', 't0_p8_points', 't0_p8_assists', 't0_p8_blocks', 't0_p8_steals', 't0_p8_reboundsTotal', 't0_p8_turnovers', 't0_p9_numMinutes', 't0_p9_points', 't0_p9_assists', 't0_p9_blocks', 't0_p9_steals', 't0_p9_reboundsTotal', 't0_p9_turnovers', 't0_p10_numMinutes', 't0_p10_points', 't0_p10_assists', 't0_p10_blocks', 't0_p10_steals', 't0_p10_reboundsTotal', 't0_p10_turnovers', 't0_p11_numMinutes', 't0_p11_points', 't0_p11_assists', 't0_p11_blocks', 't0_p11_steals', 't0_p11_reboundsTotal', 't0_p11_turnovers', 't0_p12_numMinutes', 't0_p12_points', 't0_p12_assists', 't0_p12_blocks', 't0_p12_steals', 't0_p12_reboundsTotal', 't0_p12_turnovers', 't0_p13_numMinutes', 't0_p13_points', 't0_p13_assists', 't0_p13_blocks', 't0_p13_steals', 't0_p13_reboundsTotal', 't0_p13_turnovers', 't0_p14_numMinutes', 't0_p14_points', 't0_p14_assists', 't0_p14_blocks', 't0_p14_steals', 't0_p14_reboundsTotal', 't0_p14_turnovers', 't1_p0_numMinutes', 't1_p0_points', 't1_p0_assists', 't1_p0_blocks', 't1_p0_steals', 't1_p0_reboundsTotal', 't1_p0_turnovers', 't1_p1_numMinutes', 't1_p1_points', 't1_p1_assists', 't1_p1_blocks', 't1_p1_steals', 't1_p1_reboundsTotal', 't1_p1_turnovers', 't1_p2_numMinutes', 't1_p2_points', 't1_p2_assists', 't1_p2_blocks', 't1_p2_steals', 't1_p2_reboundsTotal', 't1_p2_turnovers', 't1_p3_numMinutes', 't1_p3_points', 't1_p3_assists', 't1_p3_blocks', 't1_p3_steals', 't1_p3_reboundsTotal', 't1_p3_turnovers', 't1_p4_numMinutes', 't1_p4_points', 't1_p4_assists', 't1_p4_blocks', 't1_p4_steals', 't1_p4_reboundsTotal', 't1_p4_turnovers', 't1_p5_numMinutes', 't1_p5_points', 't1_p5_assists', 't1_p5_blocks', 't1_p5_steals', 't1_p5_reboundsTotal', 't1_p5_turnovers', 't1_p6_numMinutes', 't1_p6_points', 't1_p6_assists', 't1_p6_blocks', 't1_p6_steals', 't1_p6_reboundsTotal', 't1_p6_turnovers', 't1_p7_numMinutes', 't1_p7_points', 't1_p7_assists', 't1_p7_blocks', 't1_p7_steals', 't1_p7_reboundsTotal', 't1_p7_turnovers', 't1_p8_numMinutes', 't1_p8_points', 't1_p8_assists', 't1_p8_blocks', 't1_p8_steals', 't1_p8_reboundsTotal', 't1_p8_turnovers', 't1_p9_numMinutes', 't1_p9_points', 't1_p9_assists', 't1_p9_blocks', 't1_p9_steals', 't1_p9_reboundsTotal', 't1_p9_turnovers', 't1_p10_numMinutes', 't1_p10_points', 't1_p10_assists', 't1_p10_blocks', 't1_p10_steals', 't1_p10_reboundsTotal', 't1_p10_turnovers', 't1_p11_numMinutes', 't1_p11_points', 't1_p11_assists', 't1_p11_blocks', 't1_p11_steals', 't1_p11_reboundsTotal', 't1_p11_turnovers', 't1_p12_numMinutes', 't1_p12_points', 't1_p12_assists', 't1_p12_blocks', 't1_p12_steals', 't1_p12_reboundsTotal', 't1_p12_turnovers', 't1_p13_numMinutes', 't1_p13_points', 't1_p13_assists', 't1_p13_blocks', 't1_p13_steals', 't1_p13_reboundsTotal', 't1_p13_turnovers', 't1_p14_numMinutes', 't1_p14_points', 't1_p14_assists', 't1_p14_blocks', 't1_p14_steals', 't1_p14_reboundsTotal', 't1_p14_turnovers']
['t0_p0_numMinutespg', 't0_p0_pointspg', 't0_p0_assistspg', 't0_p0_blockspg', 't0_p0_stealspg', 't0_p0_fieldGoalsAttemptedpg', 't0_p0_fieldGoalsMadepg', 't0_p0_threePointersAttemptedpg', 't0_p0_threePointersMadepg', 't0_p0_freeThrowsAttemptedpg', 't0_p0_freeThrowsMadepg', 't0_p0_reboundsTotalpg', 't0_p0_turnoverspg', 't0_p1_numMinutespg', 't0_p1_pointspg', 't0_p1_assistspg', 't0_p1_blockspg', 't0_p1_stealspg', 't0_p1_fieldGoalsAttemptedpg', 't0_p1_fieldGoalsMadepg', 't0_p1_threePointersAttemptedpg', 't0_p1_threePointersMadepg', 't0_p1_freeThrowsAttemptedpg', 't0_p1_freeThrowsMadepg', 't0_p1_reboundsTotalpg', 't0_p1_turnoverspg', 't0_p2_numMinutespg', 't0_p2_pointspg', 't0_p2_assistspg', 't0_p2_blockspg', 't0_p2_stealspg', 't0_p2_fieldGoalsAttemptedpg', 't0_p2_fieldGoalsMadepg', 't0_p2_threePointersAttemptedpg', 't0_p2_threePointersMadepg', 't0_p2_freeThrowsAttemptedpg', 't0_p2_freeThrowsMadepg', 't0_p2_reboundsTotalpg', 't0_p2_turnoverspg', 't0_p3_numMinutespg', 't0_p3_pointspg', 't0_p3_assistspg', 't0_p3_blockspg', 't0_p3_stealspg', 't0_p3_fieldGoalsAttemptedpg', 't0_p3_fieldGoalsMadepg', 't0_p3_threePointersAttemptedpg', 't0_p3_threePointersMadepg', 't0_p3_freeThrowsAttemptedpg', 't0_p3_freeThrowsMadepg', 't0_p3_reboundsTotalpg', 't0_p3_turnoverspg', 't0_p4_numMinutespg', 't0_p4_pointspg', 't0_p4_assistspg', 't0_p4_blockspg', 't0_p4_stealspg', 't0_p4_fieldGoalsAttemptedpg', 't0_p4_fieldGoalsMadepg', 't0_p4_threePointersAttemptedpg', 't0_p4_threePointersMadepg', 't0_p4_freeThrowsAttemptedpg', 't0_p4_freeThrowsMadepg', 't0_p4_reboundsTotalpg', 't0_p4_turnoverspg', 't0_p5_numMinutespg', 't0_p5_pointspg', 't0_p5_assistspg', 't0_p5_blockspg', 't0_p5_stealspg', 't0_p5_fieldGoalsAttemptedpg', 't0_p5_fieldGoalsMadepg', 't0_p5_threePointersAttemptedpg', 't0_p5_threePointersMadepg', 't0_p5_freeThrowsAttemptedpg', 't0_p5_freeThrowsMadepg', 't0_p5_reboundsTotalpg', 't0_p5_turnoverspg', 't0_p6_numMinutespg', 't0_p6_pointspg', 't0_p6_assistspg', 't0_p6_blockspg', 't0_p6_stealspg', 't0_p6_fieldGoalsAttemptedpg', 't0_p6_fieldGoalsMadepg', 't0_p6_threePointersAttemptedpg', 't0_p6_threePointersMadepg', 't0_p6_freeThrowsAttemptedpg', 't0_p6_freeThrowsMadepg', 't0_p6_reboundsTotalpg', 't0_p6_turnoverspg', 't0_p7_numMinutespg', 't0_p7_pointspg', 't0_p7_assistspg', 't0_p7_blockspg', 't0_p7_stealspg', 't0_p7_fieldGoalsAttemptedpg', 't0_p7_fieldGoalsMadepg', 't0_p7_threePointersAttemptedpg', 't0_p7_threePointersMadepg', 't0_p7_freeThrowsAttemptedpg', 't0_p7_freeThrowsMadepg', 't0_p7_reboundsTotalpg', 't0_p7_turnoverspg', 't0_p8_numMinutespg', 't0_p8_pointspg', 't0_p8_assistspg', 't0_p8_blockspg', 't0_p8_stealspg', 't0_p8_fieldGoalsAttemptedpg', 't0_p8_fieldGoalsMadepg', 't0_p8_threePointersAttemptedpg', 't0_p8_threePointersMadepg', 't0_p8_freeThrowsAttemptedpg', 't0_p8_freeThrowsMadepg', 't0_p8_reboundsTotalpg', 't0_p8_turnoverspg', 't0_p9_numMinutespg', 't0_p9_pointspg', 't0_p9_assistspg', 't0_p9_blockspg', 't0_p9_stealspg', 't0_p9_fieldGoalsAttemptedpg', 't0_p9_fieldGoalsMadepg', 't0_p9_threePointersAttemptedpg', 't0_p9_threePointersMadepg', 't0_p9_freeThrowsAttemptedpg', 't0_p9_freeThrowsMadepg', 't0_p9_reboundsTotalpg', 't0_p9_turnoverspg', 't0_p10_numMinutespg', 't0_p10_pointspg', 't0_p10_assistspg', 't0_p10_blockspg', 't0_p10_stealspg', 't0_p10_fieldGoalsAttemptedpg', 't0_p10_fieldGoalsMadepg', 't0_p10_threePointersAttemptedpg', 't0_p10_threePointersMadepg', 't0_p10_freeThrowsAttemptedpg', 't0_p10_freeThrowsMadepg', 't0_p10_reboundsTotalpg', 't0_p10_turnoverspg', 't0_p11_numMinutespg', 't0_p11_pointspg', 't0_p11_assistspg', 't0_p11_blockspg', 't0_p11_stealspg', 't0_p11_fieldGoalsAttemptedpg', 't0_p11_fieldGoalsMadepg', 't0_p11_threePointersAttemptedpg', 't0_p11_threePointersMadepg', 't0_p11_freeThrowsAttemptedpg', 't0_p11_freeThrowsMadepg', 't0_p11_reboundsTotalpg', 't0_p11_turnoverspg', 't0_p12_numMinutespg', 't0_p12_pointspg', 't0_p12_assistspg', 't0_p12_blockspg', 't0_p12_stealspg', 't0_p12_fieldGoalsAttemptedpg', 't0_p12_fieldGoalsMadepg', 't0_p12_threePointersAttemptedpg', 't0_p12_threePointersMadepg', 't0_p12_freeThrowsAttemptedpg', 't0_p12_freeThrowsMadepg', 't0_p12_reboundsTotalpg', 't0_p12_turnoverspg', 't0_p13_numMinutespg', 't0_p13_pointspg', 't0_p13_assistspg', 't0_p13_blockspg', 't0_p13_stealspg', 't0_p13_fieldGoalsAttemptedpg', 't0_p13_fieldGoalsMadepg', 't0_p13_threePointersAttemptedpg', 't0_p13_threePointersMadepg', 't0_p13_freeThrowsAttemptedpg', 't0_p13_freeThrowsMadepg', 't0_p13_reboundsTotalpg', 't0_p13_turnoverspg', 't0_p14_numMinutespg', 't0_p14_pointspg', 't0_p14_assistspg', 't0_p14_blockspg', 't0_p14_stealspg', 't0_p14_fieldGoalsAttemptedpg', 't0_p14_fieldGoalsMadepg', 't0_p14_threePointersAttemptedpg', 't0_p14_threePointersMadepg', 't0_p14_freeThrowsAttemptedpg', 't0_p14_freeThrowsMadepg', 't0_p14_reboundsTotalpg', 't0_p14_turnoverspg', 't1_p0_numMinutespg', 't1_p0_pointspg', 't1_p0_assistspg', 't1_p0_blockspg', 't1_p0_stealspg', 't1_p0_fieldGoalsAttemptedpg', 't1_p0_fieldGoalsMadepg', 't1_p0_threePointersAttemptedpg', 't1_p0_threePointersMadepg', 't1_p0_freeThrowsAttemptedpg', 't1_p0_freeThrowsMadepg', 't1_p0_reboundsTotalpg', 't1_p0_turnoverspg', 't1_p1_numMinutespg', 't1_p1_pointspg', 't1_p1_assistspg', 't1_p1_blockspg', 't1_p1_stealspg', 't1_p1_fieldGoalsAttemptedpg', 't1_p1_fieldGoalsMadepg', 't1_p1_threePointersAttemptedpg', 't1_p1_threePointersMadepg', 't1_p1_freeThrowsAttemptedpg', 't1_p1_freeThrowsMadepg', 't1_p1_reboundsTotalpg', 't1_p1_turnoverspg', 't1_p2_numMinutespg', 't1_p2_pointspg', 't1_p2_assistspg', 't1_p2_blockspg', 't1_p2_stealspg', 't1_p2_fieldGoalsAttemptedpg', 't1_p2_fieldGoalsMadepg', 't1_p2_threePointersAttemptedpg', 't1_p2_threePointersMadepg', 't1_p2_freeThrowsAttemptedpg', 't1_p2_freeThrowsMadepg', 't1_p2_reboundsTotalpg', 't1_p2_turnoverspg', 't1_p3_numMinutespg', 't1_p3_pointspg', 't1_p3_assistspg', 't1_p3_blockspg', 't1_p3_stealspg', 't1_p3_fieldGoalsAttemptedpg', 't1_p3_fieldGoalsMadepg', 't1_p3_threePointersAttemptedpg', 't1_p3_threePointersMadepg', 't1_p3_freeThrowsAttemptedpg', 't1_p3_freeThrowsMadepg', 't1_p3_reboundsTotalpg', 't1_p3_turnoverspg', 't1_p4_numMinutespg', 't1_p4_pointspg', 't1_p4_assistspg', 't1_p4_blockspg', 't1_p4_stealspg', 't1_p4_fieldGoalsAttemptedpg', 't1_p4_fieldGoalsMadepg', 't1_p4_threePointersAttemptedpg', 't1_p4_threePointersMadepg', 't1_p4_freeThrowsAttemptedpg', 't1_p4_freeThrowsMadepg', 't1_p4_reboundsTotalpg', 't1_p4_turnoverspg', 't1_p5_numMinutespg', 't1_p5_pointspg', 't1_p5_assistspg', 't1_p5_blockspg', 't1_p5_stealspg', 't1_p5_fieldGoalsAttemptedpg', 't1_p5_fieldGoalsMadepg', 't1_p5_threePointersAttemptedpg', 't1_p5_threePointersMadepg', 't1_p5_freeThrowsAttemptedpg', 't1_p5_freeThrowsMadepg', 't1_p5_reboundsTotalpg', 't1_p5_turnoverspg', 't1_p6_numMinutespg', 't1_p6_pointspg', 't1_p6_assistspg', 't1_p6_blockspg', 't1_p6_stealspg', 't1_p6_fieldGoalsAttemptedpg', 't1_p6_fieldGoalsMadepg', 't1_p6_threePointersAttemptedpg', 't1_p6_threePointersMadepg', 't1_p6_freeThrowsAttemptedpg', 't1_p6_freeThrowsMadepg', 't1_p6_reboundsTotalpg', 't1_p6_turnoverspg', 't1_p7_numMinutespg', 't1_p7_pointspg', 't1_p7_assistspg', 't1_p7_blockspg', 't1_p7_stealspg', 't1_p7_fieldGoalsAttemptedpg', 't1_p7_fieldGoalsMadepg', 't1_p7_threePointersAttemptedpg', 't1_p7_threePointersMadepg', 't1_p7_freeThrowsAttemptedpg', 't1_p7_freeThrowsMadepg', 't1_p7_reboundsTotalpg', 't1_p7_turnoverspg', 't1_p8_numMinutespg', 't1_p8_pointspg', 't1_p8_assistspg', 't1_p8_blockspg', 't1_p8_stealspg', 't1_p8_fieldGoalsAttemptedpg', 't1_p8_fieldGoalsMadepg', 't1_p8_threePointersAttemptedpg', 't1_p8_threePointersMadepg', 't1_p8_freeThrowsAttemptedpg', 't1_p8_freeThrowsMadepg', 't1_p8_reboundsTotalpg', 't1_p8_turnoverspg', 't1_p9_numMinutespg', 't1_p9_pointspg', 't1_p9_assistspg', 't1_p9_blockspg', 't1_p9_stealspg', 't1_p9_fieldGoalsAttemptedpg', 't1_p9_fieldGoalsMadepg', 't1_p9_threePointersAttemptedpg', 't1_p9_threePointersMadepg', 't1_p9_freeThrowsAttemptedpg', 't1_p9_freeThrowsMadepg', 't1_p9_reboundsTotalpg', 't1_p9_turnoverspg', 't1_p10_numMinutespg', 't1_p10_pointspg', 't1_p10_assistspg', 't1_p10_blockspg', 't1_p10_stealspg', 't1_p10_fieldGoalsAttemptedpg', 't1_p10_fieldGoalsMadepg', 't1_p10_threePointersAttemptedpg', 't1_p10_threePointersMadepg', 't1_p10_freeThrowsAttemptedpg', 't1_p10_freeThrowsMadepg', 't1_p10_reboundsTotalpg', 't1_p10_turnoverspg', 't1_p11_numMinutespg', 't1_p11_pointspg', 't1_p11_assistspg', 't1_p11_blockspg', 't1_p11_stealspg', 't1_p11_fieldGoalsAttemptedpg', 't1_p11_fieldGoalsMadepg', 't1_p11_threePointersAttemptedpg', 't1_p11_threePointersMadepg', 't1_p11_freeThrowsAttemptedpg', 't1_p11_freeThrowsMadepg', 't1_p11_reboundsTotalpg', 't1_p11_turnoverspg', 't1_p12_numMinutespg', 't1_p12_pointspg', 't1_p12_assistspg', 't1_p12_blockspg', 't1_p12_stealspg', 't1_p12_fieldGoalsAttemptedpg', 't1_p12_fieldGoalsMadepg', 't1_p12_threePointersAttemptedpg', 't1_p12_threePointersMadepg', 't1_p12_freeThrowsAttemptedpg', 't1_p12_freeThrowsMadepg', 't1_p12_reboundsTotalpg', 't1_p12_turnoverspg', 't1_p13_numMinutespg', 't1_p13_pointspg', 't1_p13_assistspg', 't1_p13_blockspg', 't1_p13_stealspg', 't1_p13_fieldGoalsAttemptedpg', 't1_p13_fieldGoalsMadepg', 't1_p13_threePointersAttemptedpg', 't1_p13_threePointersMadepg', 't1_p13_freeThrowsAttemptedpg', 't1_p13_freeThrowsMadepg', 't1_p13_reboundsTotalpg', 't1_p13_turnoverspg', 't1_p14_numMinutespg', 't1_p14_pointspg', 't1_p14_assistspg', 't1_p14_blockspg', 't1_p14_stealspg', 't1_p14_fieldGoalsAttemptedpg', 't1_p14_fieldGoalsMadepg', 't1_p14_threePointersAttemptedpg', 't1_p14_threePointersMadepg', 't1_p14_freeThrowsAttemptedpg', 't1_p14_freeThrowsMadepg', 't1_p14_reboundsTotalpg', 't1_p14_turnoverspg']

shape: (50_646, 606)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ gameId   ┆ homeScore ┆ awayScore ┆ encodedHo ┆ … ┆ t1_p14_fr ┆ t1_p14_fr ┆ t1_p14_re ┆ t1_p14_tu │
│ ---      ┆ ---       ┆ ---       ┆ meTeam    ┆   ┆ eeThrowsA ┆ eeThrowsM ┆ boundsTot ┆ rnoverspg │
│ i64      ┆ i64       ┆ i64       ┆ ---       ┆   ┆ ttemptedp ┆ adepg     ┆ alpg      ┆ ---       │
│          ┆           ┆           ┆ i64       ┆   ┆ g         ┆ ---       ┆ ---       ┆ i32       │
│          ┆           ┆           ┆           ┆   ┆ ---       ┆ i32       ┆ i32       ┆           │
│          ┆           ┆           ┆           ┆   ┆ i32       ┆           ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 22401193 ┆ 111       ┆ 126       ┆ 11        ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0         │
│ 22401194 ┆ 132       ┆ 97        ┆ 15        ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0         │
│ 22401195 ┆ 116       ┆ 105       ┆ 18        ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0         │
│ 22401196 ┆ 100       ┆ 115       ┆ 20        ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0         │
│ 22401197 ┆ 125       ┆ 118       ┆ 28        ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0         │
│ …        ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 28000005 ┆ 85        ┆ 95        ┆ 9         ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0         │
│ 28000006 ┆ 98        ┆ 99        ┆ 30        ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0         │
│ 28000007 ┆ 130       ┆ 103       ┆ 2         ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0         │
│ 28000008 ┆ 96        ┆ 86        ┆ 32        ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0         │
│ 28000009 ┆ 91        ┆ 110       ┆ 19        ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0         │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [24]:
# max_players = None
# max_rows = 0 
# for idx, gameId in enumerate(unique_game_ids["gameId"]):
#     teams = master.filter(pl.col("gameId") == gameId).select(["encodedHomeTeam", "encodedAwayTeam"])
#     rows = box_score_with_per_game.filter((pl.col("gameId") == gameId) & (pl.col("encodedTeam").is_in([teams["encodedHomeTeam"][0], teams["encodedAwayTeam"][0]]))).shape[0]
#     if max_rows < rows:
#         max_players = box_score_with_per_game.filter((pl.col("gameId") == gameId) & (pl.col("encodedTeam").is_in([teams["encodedHomeTeam"][0], teams["encodedAwayTeam"][0]])))
#         max_rows = rows
#         print(max_rows)
#         print(max_players)

In [25]:
joined = box_score_with_per_game.join(
    master.select(["gameId", "encodedHomeTeam", "encodedAwayTeam"]),
    on="gameId",
    how="inner"
)

filtered = joined.filter(
    (pl.col("encodedTeam") == pl.col("encodedHomeTeam")) |
    (pl.col("encodedTeam") == pl.col("encodedAwayTeam"))
).fill_null(0)

player_counts = filtered.group_by("gameId").agg(
    pl.count().alias("numPlayers")
).sort(by="numPlayers", descending=True)

player_counts

/var/folders/x3/q9hsrj516xsbqf99gftzt4vr0000gn/T/ipykernel_44775/3467844820.py:13: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
  pl.count().alias("numPlayers")

shape: (50_644, 2)
┌──────────┬────────────┐
│ gameId   ┆ numPlayers │
│ ---      ┆ ---        │
│ i64      ┆ u32        │
╞══════════╪════════════╡
│ 22000230 ┆ 48         │
│ 22000123 ┆ 47         │
│ 20800840 ┆ 46         │
│ 22000789 ┆ 46         │
│ 22000748 ┆ 45         │
│ …        ┆ …          │
│ 28800843 ┆ 16         │
│ 29500512 ┆ 15         │
│ 29000999 ┆ 15         │
│ 29200067 ┆ 15         │
│ 29500294 ┆ 15         │
└──────────┴────────────┘

In [26]:
game = games.filter(pl.col("gameId") == 22400985)
game

shape: (1, 6)
┌──────────┬───────────┬───────────┬─────────────────┬─────────────────┬────────┐
│ gameId   ┆ homeScore ┆ awayScore ┆ encodedHomeTeam ┆ encodedAwayTeam ┆ season │
│ ---      ┆ ---       ┆ ---       ┆ ---             ┆ ---             ┆ ---    │
│ i64      ┆ i64       ┆ i64       ┆ i64             ┆ i64             ┆ i32    │
╞══════════╪═══════════╪═══════════╪═════════════════╪═════════════════╪════════╡
│ 22400985 ┆ 144       ┆ 137       ┆ 11              ┆ 24              ┆ 2024   │
└──────────┴───────────┴───────────┴─────────────────┴─────────────────┴────────┘

In [27]:
t0 = filtered.filter((pl.col("gameId") == 22400985) & (pl.col("encodedTeam") == 11)).sort(by="numMinutes", descending=True).limit(15)
t0

shape: (15, 39)
┌───────────┬───────────┬──────────┬──────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ firstName ┆ lastName  ┆ personId ┆ gameId   ┆ … ┆ reboundsTo ┆ turnovers ┆ encodedHo ┆ encodedAw │
│ ---       ┆ ---       ┆ ---      ┆ ---      ┆   ┆ talpg      ┆ pg        ┆ meTeam    ┆ ayTeam    │
│ str       ┆ str       ┆ i64      ┆ i64      ┆   ┆ ---        ┆ ---       ┆ ---       ┆ ---       │
│           ┆           ┆          ┆          ┆   ┆ f64        ┆ f64       ┆ i64       ┆ i64       │
╞═══════════╪═══════════╪══════════╪══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ Jalen     ┆ Green     ┆ 1630224  ┆ 22400985 ┆ … ┆ 4.567901   ┆ 2.419753  ┆ 11        ┆ 24        │
│ Dillon    ┆ Brooks    ┆ 1628415  ┆ 22400985 ┆ … ┆ 3.5        ┆ 0.935897  ┆ 11        ┆ 24        │
│ Tari      ┆ Eason     ┆ 1631106  ┆ 22400985 ┆ … ┆ 4.826667   ┆ 0.866667  ┆ 11        ┆ 24        │
│ Jabari    ┆ Smith Jr. ┆ 1631095  ┆ 22400985 ┆ … ┆ 5.25       ┆ 0.802632  ┆ 11        ┆ 24        │
│ Fred      ┆ VanVleet  ┆ 1627832  ┆ 22400985 ┆ … ┆ 2.893333   ┆ 1.133333  ┆ 11        ┆ 24        │
│ …         ┆ …         ┆ …        ┆ …        ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ Jeff      ┆ Green     ┆ 201145   ┆ 22400985 ┆ … ┆ 0.716049   ┆ 0.111111  ┆ 11        ┆ 24        │
│ Jack      ┆ McVeigh   ┆ 1629098  ┆ 22400985 ┆ … ┆ 0.217391   ┆ 0.086957  ┆ 11        ┆ 24        │
│ David     ┆ Roddy     ┆ 1631223  ┆ 22400985 ┆ … ┆ 1.0        ┆ 0.2       ┆ 11        ┆ 24        │
│ David     ┆ Roddy     ┆ 1631223  ┆ 22400985 ┆ … ┆ 1.4        ┆ 0.4       ┆ 11        ┆ 24        │
│ David     ┆ Roddy     ┆ 1631223  ┆ 22400985 ┆ … ┆ 2.25       ┆ 0.25      ┆ 11        ┆ 24        │
└───────────┴───────────┴──────────┴──────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [28]:
t1 = filtered.filter((pl.col("gameId") == 22400985) & (pl.col("encodedTeam") == 24)).sort(by="numMinutes", descending=True).limit(15)
t1

shape: (15, 39)
┌───────────┬────────────┬──────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ firstName ┆ lastName   ┆ personId ┆ gameId   ┆ … ┆ reboundsT ┆ turnovers ┆ encodedHo ┆ encodedAw │
│ ---       ┆ ---        ┆ ---      ┆ ---      ┆   ┆ otalpg    ┆ pg        ┆ meTeam    ┆ ayTeam    │
│ str       ┆ str        ┆ i64      ┆ i64      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│           ┆            ┆          ┆          ┆   ┆ f64       ┆ f64       ┆ i64       ┆ i64       │
╞═══════════╪════════════╪══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ Quentin   ┆ Grimes     ┆ 1629656  ┆ 22400985 ┆ … ┆ 4.53125   ┆ 2.5       ┆ 11        ┆ 24        │
│ Quentin   ┆ Grimes     ┆ 1629656  ┆ 22400985 ┆ … ┆ 3.729167  ┆ 1.270833  ┆ 11        ┆ 24        │
│ Oshae     ┆ Brissett   ┆ 1629052  ┆ 22400985 ┆ … ┆ 3.666667  ┆ 1.333333  ┆ 11        ┆ 24        │
│ Justin    ┆ Edwards    ┆ 1642348  ┆ 22400985 ┆ … ┆ 2.466667  ┆ 0.816667  ┆ 11        ┆ 24        │
│ Jared     ┆ Butler     ┆ 1630215  ┆ 22400985 ┆ … ┆ 2.225806  ┆ 1.645161  ┆ 11        ┆ 24        │
│ …         ┆ …          ┆ …        ┆ …        ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ Chuma     ┆ Okeke      ┆ 1629643  ┆ 22400985 ┆ … ┆ 0.8       ┆ 0.0       ┆ 11        ┆ 24        │
│ Jeff      ┆ Dowtin Jr. ┆ 1630288  ┆ 22400985 ┆ … ┆ 1.2       ┆ 0.3       ┆ 11        ┆ 24        │
│ Alex      ┆ Reese      ┆ 1642024  ┆ 22400985 ┆ … ┆ 3.066667  ┆ 0.4       ┆ 11        ┆ 24        │
│ Alex      ┆ Reese      ┆ 1642024  ┆ 22400985 ┆ … ┆ 0.25      ┆ 0.0       ┆ 11        ┆ 24        │
│ Kyle      ┆ Lowry      ┆ 200768   ┆ 22400985 ┆ … ┆ 1.717949  ┆ 0.538462  ┆ 11        ┆ 24        │
└───────────┴────────────┴──────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [29]:
features = filtered.drop(["playerteamCity",	"playerteamName",	"opponentteamCity",	"opponentteamName", "season", "encodedHomeTeam",	"encodedAwayTeam",])
col_to_move = "encodedTeam"
target_index = 4

# Create new column order
cols = features.columns.copy()
cols.remove(col_to_move)
cols.insert(target_index, col_to_move)

# Reorder DataFrame
features = features.select(cols)
features.filter((pl.col("firstName") == "Stephen") & (pl.col("pointspg") > 29))

shape: (56, 32)
┌───────────┬──────────┬──────────┬──────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ firstName ┆ lastName ┆ personId ┆ gameId   ┆ … ┆ freeThrows ┆ freeThrows ┆ reboundsT ┆ turnovers │
│ ---       ┆ ---      ┆ ---      ┆ ---      ┆   ┆ Attemptedp ┆ Madepg     ┆ otalpg    ┆ pg        │
│ str       ┆ str      ┆ i64      ┆ i64      ┆   ┆ g          ┆ ---        ┆ ---       ┆ ---       │
│           ┆          ┆          ┆          ┆   ┆ ---        ┆ f64        ┆ f64       ┆ f64       │
│           ┆          ┆          ┆          ┆   ┆ f64        ┆            ┆           ┆           │
╞═══════════╪══════════╪══════════╪══════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ Stephen   ┆ Curry    ┆ 201939   ┆ 22201230 ┆ … ┆ 5.017857   ┆ 4.589286   ┆ 6.089286  ┆ 3.196429  │
│ Stephen   ┆ Curry    ┆ 201939   ┆ 22201211 ┆ … ┆ 5.017857   ┆ 4.589286   ┆ 6.089286  ┆ 3.196429  │
│ Stephen   ┆ Curry    ┆ 201939   ┆ 22201187 ┆ … ┆ 5.017857   ┆ 4.589286   ┆ 6.089286  ┆ 3.196429  │
│ Stephen   ┆ Curry    ┆ 201939   ┆ 22201175 ┆ … ┆ 5.017857   ┆ 4.589286   ┆ 6.089286  ┆ 3.196429  │
│ Stephen   ┆ Curry    ┆ 201939   ┆ 22201158 ┆ … ┆ 5.017857   ┆ 4.589286   ┆ 6.089286  ┆ 3.196429  │
│ …         ┆ …        ┆ …        ┆ …        ┆ … ┆ …          ┆ …          ┆ …         ┆ …         │
│ Stephen   ┆ Curry    ┆ 201939   ┆ 22200068 ┆ … ┆ 5.017857   ┆ 4.589286   ┆ 6.089286  ┆ 3.196429  │
│ Stephen   ┆ Curry    ┆ 201939   ┆ 22200055 ┆ … ┆ 5.017857   ┆ 4.589286   ┆ 6.089286  ┆ 3.196429  │
│ Stephen   ┆ Curry    ┆ 201939   ┆ 22200042 ┆ … ┆ 5.017857   ┆ 4.589286   ┆ 6.089286  ┆ 3.196429  │
│ Stephen   ┆ Curry    ┆ 201939   ┆ 22200026 ┆ … ┆ 5.017857   ┆ 4.589286   ┆ 6.089286  ┆ 3.196429  │
│ Stephen   ┆ Curry    ┆ 201939   ┆ 22200002 ┆ … ┆ 5.017857   ┆ 4.589286   ┆ 6.089286  ┆ 3.196429  │
└───────────┴──────────┴──────────┴──────────┴───┴────────────┴────────────┴───────────┴───────────┘

In [30]:
master.schema

Schema([('gameId', Int64),
        ('homeScore', Int64),
        ('awayScore', Int64),
        ('encodedHomeTeam', Int64),
        ('encodedAwayTeam', Int64),
        ('season', Int32),
        ('t0_p0_numMinutes', Int32),
        ('t0_p0_points', Int32),
        ('t0_p0_assists', Int32),
        ('t0_p0_blocks', Int32),
        ('t0_p0_steals', Int32),
        ('t0_p0_reboundsTotal', Int32),
        ('t0_p0_turnovers', Int32),
        ('t0_p1_numMinutes', Int32),
        ('t0_p1_points', Int32),
        ('t0_p1_assists', Int32),
        ('t0_p1_blocks', Int32),
        ('t0_p1_steals', Int32),
        ('t0_p1_reboundsTotal', Int32),
        ('t0_p1_turnovers', Int32),
        ('t0_p2_numMinutes', Int32),
        ('t0_p2_points', Int32),
        ('t0_p2_assists', Int32),
        ('t0_p2_blocks', Int32),
        ('t0_p2_steals', Int32),
        ('t0_p2_reboundsTotal', Int32),
        ('t0_p2_turnovers', Int32),
        ('t0_p3_numMinutes', Int32),
        ('t0_p3_points', Int32),
        ('t0_p3_assists', Int32),
        ('t0_p3_blocks', Int32),
        ('t0_p3_steals', Int32),
        ('t0_p3_reboundsTotal', Int32),
        ('t0_p3_turnovers', Int32),
        ('t0_p4_numMinutes', Int32),
        ('t0_p4_points', Int32),
        ('t0_p4_assists', Int32),
        ('t0_p4_blocks', Int32),
        ('t0_p4_steals', Int32),
        ('t0_p4_reboundsTotal', Int32),
        ('t0_p4_turnovers', Int32),
        ('t0_p5_numMinutes', Int32),
        ('t0_p5_points', Int32),
        ('t0_p5_assists', Int32),
        ('t0_p5_blocks', Int32),
        ('t0_p5_steals', Int32),
        ('t0_p5_reboundsTotal', Int32),
        ('t0_p5_turnovers', Int32),
        ('t0_p6_numMinutes', Int32),
        ('t0_p6_points', Int32),
        ('t0_p6_assists', Int32),
        ('t0_p6_blocks', Int32),
        ('t0_p6_steals', Int32),
        ('t0_p6_reboundsTotal', Int32),
        ('t0_p6_turnovers', Int32),
        ('t0_p7_numMinutes', Int32),
        ('t0_p7_points', Int32),
        ('t0_p7_assists', Int32),
        ('t0_p7_blocks', Int32),
        ('t0_p7_steals', Int32),
        ('t0_p7_reboundsTotal', Int32),
        ('t0_p7_turnovers', Int32),
        ('t0_p8_numMinutes', Int32),
        ('t0_p8_points', Int32),
        ('t0_p8_assists', Int32),
        ('t0_p8_blocks', Int32),
        ('t0_p8_steals', Int32),
        ('t0_p8_reboundsTotal', Int32),
        ('t0_p8_turnovers', Int32),
        ('t0_p9_numMinutes', Int32),
        ('t0_p9_points', Int32),
        ('t0_p9_assists', Int32),
        ('t0_p9_blocks', Int32),
        ('t0_p9_steals', Int32),
        ('t0_p9_reboundsTotal', Int32),
        ('t0_p9_turnovers', Int32),
        ('t0_p10_numMinutes', Int32),
        ('t0_p10_points', Int32),
        ('t0_p10_assists', Int32),
        ('t0_p10_blocks', Int32),
        ('t0_p10_steals', Int32),
        ('t0_p10_reboundsTotal', Int32),
        ('t0_p10_turnovers', Int32),
        ('t0_p11_numMinutes', Int32),
        ('t0_p11_points', Int32),
        ('t0_p11_assists', Int32),
        ('t0_p11_blocks', Int32),
        ('t0_p11_steals', Int32),
        ('t0_p11_reboundsTotal', Int32),
        ('t0_p11_turnovers', Int32),
        ('t0_p12_numMinutes', Int32),
        ('t0_p12_points', Int32),
        ('t0_p12_assists', Int32),
        ('t0_p12_blocks', Int32),
        ('t0_p12_steals', Int32),
        ('t0_p12_reboundsTotal', Int32),
        ('t0_p12_turnovers', Int32),
        ('t0_p13_numMinutes', Int32),
        ('t0_p13_points', Int32),
        ('t0_p13_assists', Int32),
        ('t0_p13_blocks', Int32),
        ('t0_p13_steals', Int32),
        ('t0_p13_reboundsTotal', Int32),
        ('t0_p13_turnovers', Int32),
        ('t0_p14_numMinutes', Int32),
        ('t0_p14_points', Int32),
        ('t0_p14_assists', Int32),
        ('t0_p14_blocks', Int32),
        ('t0_p14_steals', Int32),
        ('t0_p14_reboundsTotal', Int32),
        ('t0_p14_turnovers', Int32),
        ('t1_p0_numMinutes', Int32),
        ('t1_p0_points', Int32),
        ('t1_p0_assists', Int32),
        ('t1_p0_blocks', Int32),
        ('t1_p0_steals', Int32),
        ('t1_p0_reboundsTotal', Int32),
        ('t1_p0_turnovers', Int32),
        ('t1_p1_numMinutes', Int32),
        ('t1_p1_points', Int32),
        ('t1_p1_assists', Int32),
        ('t1_p1_blocks', Int32),
        ('t1_p1_steals', Int32),
        ('t1_p1_reboundsTotal', Int32),
        ('t1_p1_turnovers', Int32),
        ('t1_p2_numMinutes', Int32),
        ('t1_p2_points', Int32),
        ('t1_p2_assists', Int32),
        ('t1_p2_blocks', Int32),
        ('t1_p2_steals', Int32),
        ('t1_p2_reboundsTotal', Int32),
        ('t1_p2_turnovers', Int32),
        ('t1_p3_numMinutes', Int32),
        ('t1_p3_points', Int32),
        ('t1_p3_assists', Int32),
        ('t1_p3_blocks', Int32),
        ('t1_p3_steals', Int32),
        ('t1_p3_reboundsTotal', Int32),
        ('t1_p3_turnovers', Int32),
        ('t1_p4_numMinutes', Int32),
        ('t1_p4_points', Int32),
        ('t1_p4_assists', Int32),
        ('t1_p4_blocks', Int32),
        ('t1_p4_steals', Int32),
        ('t1_p4_reboundsTotal', Int32),
        ('t1_p4_turnovers', Int32),
        ('t1_p5_numMinutes', Int32),
        ('t1_p5_points', Int32),
        ('t1_p5_assists', Int32),
        ('t1_p5_blocks', Int32),
        ('t1_p5_steals', Int32),
        ('t1_p5_reboundsTotal', Int32),
        ('t1_p5_turnovers', Int32),
        ('t1_p6_numMinutes', Int32),
        ('t1_p6_points', Int32),
        ('t1_p6_assists', Int32),
        ('t1_p6_blocks', Int32),
        ('t1_p6_steals', Int32),
        ('t1_p6_reboundsTotal', Int32),
        ('t1_p6_turnovers', Int32),
        ('t1_p7_numMinutes', Int32),
        ('t1_p7_points', Int32),
        ('t1_p7_assists', Int32),
        ('t1_p7_blocks', Int32),
        ('t1_p7_steals', Int32),
        ('t1_p7_reboundsTotal', Int32),
        ('t1_p7_turnovers', Int32),
        ('t1_p8_numMinutes', Int32),
        ('t1_p8_points', Int32),
        ('t1_p8_assists', Int32),
        ('t1_p8_blocks', Int32),
        ('t1_p8_steals', Int32),
        ('t1_p8_reboundsTotal', Int32),
        ('t1_p8_turnovers', Int32),
        ('t1_p9_numMinutes', Int32),
        ('t1_p9_points', Int32),
        ('t1_p9_assists', Int32),
        ('t1_p9_blocks', Int32),
        ('t1_p9_steals', Int32),
        ('t1_p9_reboundsTotal', Int32),
        ('t1_p9_turnovers', Int32),
        ('t1_p10_numMinutes', Int32),
        ('t1_p10_points', Int32),
        ('t1_p10_assists', Int32),
        ('t1_p10_blocks', Int32),
        ('t1_p10_steals', Int32),
        ('t1_p10_reboundsTotal', Int32),
        ('t1_p10_turnovers', Int32),
        ('t1_p11_numMinutes', Int32),
        ('t1_p11_points', Int32),
        ('t1_p11_assists', Int32),
        ('t1_p11_blocks', Int32),
        ('t1_p11_steals', Int32),
        ('t1_p11_reboundsTotal', Int32),
        ('t1_p11_turnovers', Int32),
        ('t1_p12_numMinutes', Int32),
        ('t1_p12_points', Int32),
        ('t1_p12_assists', Int32),
        ('t1_p12_blocks', Int32),
        ('t1_p12_steals', Int32),
        ('t1_p12_reboundsTotal', Int32),
        ('t1_p12_turnovers', Int32),
        ('t1_p13_numMinutes', Int32),
        ('t1_p13_points', Int32),
        ('t1_p13_assists', Int32),
        ('t1_p13_blocks', Int32),
        ('t1_p13_steals', Int32),
        ('t1_p13_reboundsTotal', Int32),
        ('t1_p13_turnovers', Int32),
        ('t1_p14_numMinutes', Int32),
        ('t1_p14_points', Int32),
        ('t1_p14_assists', Int32),
        ('t1_p14_blocks', Int32),
        ('t1_p14_steals', Int32),
        ('t1_p14_reboundsTotal', Int32),
        ('t1_p14_turnovers', Int32),
        ('t0_p0_numMinutespg', Int32),
        ('t0_p0_pointspg', Int32),
        ('t0_p0_assistspg', Int32),
        ('t0_p0_blockspg', Int32),
        ('t0_p0_stealspg', Int32),
        ('t0_p0_fieldGoalsAttemptedpg', Int32),
        ('t0_p0_fieldGoalsMadepg', Int32),
        ('t0_p0_threePointersAttemptedpg', Int32),
        ('t0_p0_threePointersMadepg', Int32),
        ('t0_p0_freeThrowsAttemptedpg', Int32),
        ('t0_p0_freeThrowsMadepg', Int32),
        ('t0_p0_reboundsTotalpg', Int32),
        ('t0_p0_turnoverspg', Int32),
        ('t0_p1_numMinutespg', Int32),
        ('t0_p1_pointspg', Int32),
        ('t0_p1_assistspg', Int32),
        ('t0_p1_blockspg', Int32),
        ('t0_p1_stealspg', Int32),
        ('t0_p1_fieldGoalsAttemptedpg', Int32),
        ('t0_p1_fieldGoalsMadepg', Int32),
        ('t0_p1_threePointersAttemptedpg', Int32),
        ('t0_p1_threePointersMadepg', Int32),
        ('t0_p1_freeThrowsAttemptedpg', Int32),
        ('t0_p1_freeThrowsMadepg', Int32),
        ('t0_p1_reboundsTotalpg', Int32),
        ('t0_p1_turnoverspg', Int32),
        ('t0_p2_numMinutespg', Int32),
        ('t0_p2_pointspg', Int32),
        ('t0_p2_assistspg', Int32),
        ('t0_p2_blockspg', Int32),
        ('t0_p2_stealspg', Int32),
        ('t0_p2_fieldGoalsAttemptedpg', Int32),
        ('t0_p2_fieldGoalsMadepg', Int32),
        ('t0_p2_threePointersAttemptedpg', Int32),
        ('t0_p2_threePointersMadepg', Int32),
        ('t0_p2_freeThrowsAttemptedpg', Int32),
        ('t0_p2_freeThrowsMadepg', Int32),
        ('t0_p2_reboundsTotalpg', Int32),
        ('t0_p2_turnoverspg', Int32),
        ('t0_p3_numMinutespg', Int32),
        ('t0_p3_pointspg', Int32),
        ('t0_p3_assistspg', Int32),
        ('t0_p3_blockspg', Int32),
        ('t0_p3_stealspg', Int32),
        ('t0_p3_fieldGoalsAttemptedpg', Int32),
        ('t0_p3_fieldGoalsMadepg', Int32),
        ('t0_p3_threePointersAttemptedpg', Int32),
        ('t0_p3_threePointersMadepg', Int32),
        ('t0_p3_freeThrowsAttemptedpg', Int32),
        ('t0_p3_freeThrowsMadepg', Int32),
        ('t0_p3_reboundsTotalpg', Int32),
        ('t0_p3_turnoverspg', Int32),
        ('t0_p4_numMinutespg', Int32),
        ('t0_p4_pointspg', Int32),
        ('t0_p4_assistspg', Int32),
        ('t0_p4_blockspg', Int32),
        ('t0_p4_stealspg', Int32),
        ('t0_p4_fieldGoalsAttemptedpg', Int32),
        ('t0_p4_fieldGoalsMadepg', Int32),
        ('t0_p4_threePointersAttemptedpg', Int32),
        ('t0_p4_threePointersMadepg', Int32),
        ('t0_p4_freeThrowsAttemptedpg', Int32),
        ('t0_p4_freeThrowsMadepg', Int32),
        ('t0_p4_reboundsTotalpg', Int32),
        ('t0_p4_turnoverspg', Int32),
        ('t0_p5_numMinutespg', Int32),
        ('t0_p5_pointspg', Int32),
        ('t0_p5_assistspg', Int32),
        ('t0_p5_blockspg', Int32),
        ('t0_p5_stealspg', Int32),
        ('t0_p5_fieldGoalsAttemptedpg', Int32),
        ('t0_p5_fieldGoalsMadepg', Int32),
        ('t0_p5_threePointersAttemptedpg', Int32),
        ('t0_p5_threePointersMadepg', Int32),
        ('t0_p5_freeThrowsAttemptedpg', Int32),
        ('t0_p5_freeThrowsMadepg', Int32),
        ('t0_p5_reboundsTotalpg', Int32),
        ('t0_p5_turnoverspg', Int32),
        ('t0_p6_numMinutespg', Int32),
        ('t0_p6_pointspg', Int32),
        ('t0_p6_assistspg', Int32),
        ('t0_p6_blockspg', Int32),
        ('t0_p6_stealspg', Int32),
        ('t0_p6_fieldGoalsAttemptedpg', Int32),
        ('t0_p6_fieldGoalsMadepg', Int32),
        ('t0_p6_threePointersAttemptedpg', Int32),
        ('t0_p6_threePointersMadepg', Int32),
        ('t0_p6_freeThrowsAttemptedpg', Int32),
        ('t0_p6_freeThrowsMadepg', Int32),
        ('t0_p6_reboundsTotalpg', Int32),
        ('t0_p6_turnoverspg', Int32),
        ('t0_p7_numMinutespg', Int32),
        ('t0_p7_pointspg', Int32),
        ('t0_p7_assistspg', Int32),
        ('t0_p7_blockspg', Int32),
        ('t0_p7_stealspg', Int32),
        ('t0_p7_fieldGoalsAttemptedpg', Int32),
        ('t0_p7_fieldGoalsMadepg', Int32),
        ('t0_p7_threePointersAttemptedpg', Int32),
        ('t0_p7_threePointersMadepg', Int32),
        ('t0_p7_freeThrowsAttemptedpg', Int32),
        ('t0_p7_freeThrowsMadepg', Int32),
        ('t0_p7_reboundsTotalpg', Int32),
        ('t0_p7_turnoverspg', Int32),
        ('t0_p8_numMinutespg', Int32),
        ('t0_p8_pointspg', Int32),
        ('t0_p8_assistspg', Int32),
        ('t0_p8_blockspg', Int32),
        ('t0_p8_stealspg', Int32),
        ('t0_p8_fieldGoalsAttemptedpg', Int32),
        ('t0_p8_fieldGoalsMadepg', Int32),
        ('t0_p8_threePointersAttemptedpg', Int32),
        ('t0_p8_threePointersMadepg', Int32),
        ('t0_p8_freeThrowsAttemptedpg', Int32),
        ('t0_p8_freeThrowsMadepg', Int32),
        ('t0_p8_reboundsTotalpg', Int32),
        ('t0_p8_turnoverspg', Int32),
        ('t0_p9_numMinutespg', Int32),
        ('t0_p9_pointspg', Int32),
        ('t0_p9_assistspg', Int32),
        ('t0_p9_blockspg', Int32),
        ('t0_p9_stealspg', Int32),
        ('t0_p9_fieldGoalsAttemptedpg', Int32),
        ('t0_p9_fieldGoalsMadepg', Int32),
        ('t0_p9_threePointersAttemptedpg', Int32),
        ('t0_p9_threePointersMadepg', Int32),
        ('t0_p9_freeThrowsAttemptedpg', Int32),
        ('t0_p9_freeThrowsMadepg', Int32),
        ('t0_p9_reboundsTotalpg', Int32),
        ('t0_p9_turnoverspg', Int32),
        ('t0_p10_numMinutespg', Int32),
        ('t0_p10_pointspg', Int32),
        ('t0_p10_assistspg', Int32),
        ('t0_p10_blockspg', Int32),
        ('t0_p10_stealspg', Int32),
        ('t0_p10_fieldGoalsAttemptedpg', Int32),
        ('t0_p10_fieldGoalsMadepg', Int32),
        ('t0_p10_threePointersAttemptedpg', Int32),
        ('t0_p10_threePointersMadepg', Int32),
        ('t0_p10_freeThrowsAttemptedpg', Int32),
        ('t0_p10_freeThrowsMadepg', Int32),
        ('t0_p10_reboundsTotalpg', Int32),
        ('t0_p10_turnoverspg', Int32),
        ('t0_p11_numMinutespg', Int32),
        ('t0_p11_pointspg', Int32),
        ('t0_p11_assistspg', Int32),
        ('t0_p11_blockspg', Int32),
        ('t0_p11_stealspg', Int32),
        ('t0_p11_fieldGoalsAttemptedpg', Int32),
        ('t0_p11_fieldGoalsMadepg', Int32),
        ('t0_p11_threePointersAttemptedpg', Int32),
        ('t0_p11_threePointersMadepg', Int32),
        ('t0_p11_freeThrowsAttemptedpg', Int32),
        ('t0_p11_freeThrowsMadepg', Int32),
        ('t0_p11_reboundsTotalpg', Int32),
        ('t0_p11_turnoverspg', Int32),
        ('t0_p12_numMinutespg', Int32),
        ('t0_p12_pointspg', Int32),
        ('t0_p12_assistspg', Int32),
        ('t0_p12_blockspg', Int32),
        ('t0_p12_stealspg', Int32),
        ('t0_p12_fieldGoalsAttemptedpg', Int32),
        ('t0_p12_fieldGoalsMadepg', Int32),
        ('t0_p12_threePointersAttemptedpg', Int32),
        ('t0_p12_threePointersMadepg', Int32),
        ('t0_p12_freeThrowsAttemptedpg', Int32),
        ('t0_p12_freeThrowsMadepg', Int32),
        ('t0_p12_reboundsTotalpg', Int32),
        ('t0_p12_turnoverspg', Int32),
        ('t0_p13_numMinutespg', Int32),
        ('t0_p13_pointspg', Int32),
        ('t0_p13_assistspg', Int32),
        ('t0_p13_blockspg', Int32),
        ('t0_p13_stealspg', Int32),
        ('t0_p13_fieldGoalsAttemptedpg', Int32),
        ('t0_p13_fieldGoalsMadepg', Int32),
        ('t0_p13_threePointersAttemptedpg', Int32),
        ('t0_p13_threePointersMadepg', Int32),
        ('t0_p13_freeThrowsAttemptedpg', Int32),
        ('t0_p13_freeThrowsMadepg', Int32),
        ('t0_p13_reboundsTotalpg', Int32),
        ('t0_p13_turnoverspg', Int32),
        ('t0_p14_numMinutespg', Int32),
        ('t0_p14_pointspg', Int32),
        ('t0_p14_assistspg', Int32),
        ('t0_p14_blockspg', Int32),
        ('t0_p14_stealspg', Int32),
        ('t0_p14_fieldGoalsAttemptedpg', Int32),
        ('t0_p14_fieldGoalsMadepg', Int32),
        ('t0_p14_threePointersAttemptedpg', Int32),
        ('t0_p14_threePointersMadepg', Int32),
        ('t0_p14_freeThrowsAttemptedpg', Int32),
        ('t0_p14_freeThrowsMadepg', Int32),
        ('t0_p14_reboundsTotalpg', Int32),
        ('t0_p14_turnoverspg', Int32),
        ('t1_p0_numMinutespg', Int32),
        ('t1_p0_pointspg', Int32),
        ('t1_p0_assistspg', Int32),
        ('t1_p0_blockspg', Int32),
        ('t1_p0_stealspg', Int32),
        ('t1_p0_fieldGoalsAttemptedpg', Int32),
        ('t1_p0_fieldGoalsMadepg', Int32),
        ('t1_p0_threePointersAttemptedpg', Int32),
        ('t1_p0_threePointersMadepg', Int32),
        ('t1_p0_freeThrowsAttemptedpg', Int32),
        ('t1_p0_freeThrowsMadepg', Int32),
        ('t1_p0_reboundsTotalpg', Int32),
        ('t1_p0_turnoverspg', Int32),
        ('t1_p1_numMinutespg', Int32),
        ('t1_p1_pointspg', Int32),
        ('t1_p1_assistspg', Int32),
        ('t1_p1_blockspg', Int32),
        ('t1_p1_stealspg', Int32),
        ('t1_p1_fieldGoalsAttemptedpg', Int32),
        ('t1_p1_fieldGoalsMadepg', Int32),
        ('t1_p1_threePointersAttemptedpg', Int32),
        ('t1_p1_threePointersMadepg', Int32),
        ('t1_p1_freeThrowsAttemptedpg', Int32),
        ('t1_p1_freeThrowsMadepg', Int32),
        ('t1_p1_reboundsTotalpg', Int32),
        ('t1_p1_turnoverspg', Int32),
        ('t1_p2_numMinutespg', Int32),
        ('t1_p2_pointspg', Int32),
        ('t1_p2_assistspg', Int32),
        ('t1_p2_blockspg', Int32),
        ('t1_p2_stealspg', Int32),
        ('t1_p2_fieldGoalsAttemptedpg', Int32),
        ('t1_p2_fieldGoalsMadepg', Int32),
        ('t1_p2_threePointersAttemptedpg', Int32),
        ('t1_p2_threePointersMadepg', Int32),
        ('t1_p2_freeThrowsAttemptedpg', Int32),
        ('t1_p2_freeThrowsMadepg', Int32),
        ('t1_p2_reboundsTotalpg', Int32),
        ('t1_p2_turnoverspg', Int32),
        ('t1_p3_numMinutespg', Int32),
        ('t1_p3_pointspg', Int32),
        ('t1_p3_assistspg', Int32),
        ('t1_p3_blockspg', Int32),
        ('t1_p3_stealspg', Int32),
        ('t1_p3_fieldGoalsAttemptedpg', Int32),
        ('t1_p3_fieldGoalsMadepg', Int32),
        ('t1_p3_threePointersAttemptedpg', Int32),
        ('t1_p3_threePointersMadepg', Int32),
        ('t1_p3_freeThrowsAttemptedpg', Int32),
        ('t1_p3_freeThrowsMadepg', Int32),
        ('t1_p3_reboundsTotalpg', Int32),
        ('t1_p3_turnoverspg', Int32),
        ('t1_p4_numMinutespg', Int32),
        ('t1_p4_pointspg', Int32),
        ('t1_p4_assistspg', Int32),
        ('t1_p4_blockspg', Int32),
        ('t1_p4_stealspg', Int32),
        ('t1_p4_fieldGoalsAttemptedpg', Int32),
        ('t1_p4_fieldGoalsMadepg', Int32),
        ('t1_p4_threePointersAttemptedpg', Int32),
        ('t1_p4_threePointersMadepg', Int32),
        ('t1_p4_freeThrowsAttemptedpg', Int32),
        ('t1_p4_freeThrowsMadepg', Int32),
        ('t1_p4_reboundsTotalpg', Int32),
        ('t1_p4_turnoverspg', Int32),
        ('t1_p5_numMinutespg', Int32),
        ('t1_p5_pointspg', Int32),
        ('t1_p5_assistspg', Int32),
        ('t1_p5_blockspg', Int32),
        ('t1_p5_stealspg', Int32),
        ('t1_p5_fieldGoalsAttemptedpg', Int32),
        ('t1_p5_fieldGoalsMadepg', Int32),
        ('t1_p5_threePointersAttemptedpg', Int32),
        ('t1_p5_threePointersMadepg', Int32),
        ('t1_p5_freeThrowsAttemptedpg', Int32),
        ('t1_p5_freeThrowsMadepg', Int32),
        ('t1_p5_reboundsTotalpg', Int32),
        ('t1_p5_turnoverspg', Int32),
        ('t1_p6_numMinutespg', Int32),
        ('t1_p6_pointspg', Int32),
        ('t1_p6_assistspg', Int32),
        ('t1_p6_blockspg', Int32),
        ('t1_p6_stealspg', Int32),
        ('t1_p6_fieldGoalsAttemptedpg', Int32),
        ('t1_p6_fieldGoalsMadepg', Int32),
        ('t1_p6_threePointersAttemptedpg', Int32),
        ('t1_p6_threePointersMadepg', Int32),
        ('t1_p6_freeThrowsAttemptedpg', Int32),
        ('t1_p6_freeThrowsMadepg', Int32),
        ('t1_p6_reboundsTotalpg', Int32),
        ('t1_p6_turnoverspg', Int32),
        ('t1_p7_numMinutespg', Int32),
        ('t1_p7_pointspg', Int32),
        ('t1_p7_assistspg', Int32),
        ('t1_p7_blockspg', Int32),
        ('t1_p7_stealspg', Int32),
        ('t1_p7_fieldGoalsAttemptedpg', Int32),
        ('t1_p7_fieldGoalsMadepg', Int32),
        ('t1_p7_threePointersAttemptedpg', Int32),
        ('t1_p7_threePointersMadepg', Int32),
        ('t1_p7_freeThrowsAttemptedpg', Int32),

In [31]:
features.schema

Schema([('firstName', String),
        ('lastName', String),
        ('personId', Int64),
        ('gameId', Int64),
        ('encodedTeam', Int64),
        ('numMinutes', Float64),
        ('points', Float64),
        ('assists', Float64),
        ('blocks', Float64),
        ('steals', Float64),
        ('fieldGoalsAttempted', Float64),
        ('fieldGoalsMade', Float64),
        ('threePointersAttempted', Float64),
        ('threePointersMade', Float64),
        ('freeThrowsAttempted', Float64),
        ('freeThrowsMade', Float64),
        ('reboundsTotal', Float64),
        ('turnovers', Float64),
        ('encodedTeampg', UInt32),
        ('numMinutespg', Float64),
        ('pointspg', Float64),
        ('assistspg', Float64),
        ('blockspg', Float64),
        ('stealspg', Float64),
        ('fieldGoalsAttemptedpg', Float64),
        ('fieldGoalsMadepg', Float64),
        ('threePointersAttemptedpg', Float64),
        ('threePointersMadepg', Float64),
        ('freeThrowsAttemptedpg', Float64),
        ('freeThrowsMadepg', Float64),
        ('reboundsTotalpg', Float64),
        ('turnoverspg', Float64)])

In [32]:
features.filter((pl.col("gameId") == 22201230) & (pl.col("encodedTeam" ) == 10)).sort(by="numMinutes", descending=True)

shape: (14, 32)
┌───────────┬────────────┬──────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ firstName ┆ lastName   ┆ personId ┆ gameId   ┆ … ┆ freeThrow ┆ freeThrow ┆ reboundsT ┆ turnovers │
│ ---       ┆ ---        ┆ ---      ┆ ---      ┆   ┆ sAttempte ┆ sMadepg   ┆ otalpg    ┆ pg        │
│ str       ┆ str        ┆ i64      ┆ i64      ┆   ┆ dpg       ┆ ---       ┆ ---       ┆ ---       │
│           ┆            ┆          ┆          ┆   ┆ ---       ┆ f64       ┆ f64       ┆ f64       │
│           ┆            ┆          ┆          ┆   ┆ f64       ┆           ┆           ┆           │
╞═══════════╪════════════╪══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ Moses     ┆ Moody      ┆ 1630541  ┆ 22201230 ┆ … ┆ 0.670886  ┆ 0.468354  ┆ 1.329114  ┆ 0.43038   │
│ Jonathan  ┆ Kuminga    ┆ 1630228  ┆ 22201230 ┆ … ┆ 1.943662  ┆ 1.267606  ┆ 3.253521  ┆ 1.338028  │
│ Stephen   ┆ Curry      ┆ 201939   ┆ 22201230 ┆ … ┆ 5.017857  ┆ 4.589286  ┆ 6.089286  ┆ 3.196429  │
│ Klay      ┆ Thompson   ┆ 202691   ┆ 22201230 ┆ … ┆ 1.808219  ┆ 1.589041  ┆ 3.917808  ┆ 1.684932  │
│ Kevon     ┆ Looney     ┆ 1626172  ┆ 22201230 ┆ … ┆ 1.890244  ┆ 1.146341  ┆ 9.268293  ┆ 0.54878   │
│ …         ┆ …          ┆ …        ┆ …        ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ Jordan    ┆ Poole      ┆ 1629673  ┆ 22201230 ┆ … ┆ 5.060976  ┆ 4.402439  ┆ 2.743902  ┆ 3.073171  │
│ JaMychal  ┆ Green      ┆ 203210   ┆ 22201230 ┆ … ┆ 0.985294  ┆ 0.764706  ┆ 3.014706  ┆ 0.764706  │
│ Anthony   ┆ Lamb       ┆ 1630237  ┆ 22201230 ┆ … ┆ 0.967742  ┆ 0.741935  ┆ 3.467742  ┆ 0.870968  │
│ Lester    ┆ Quinones   ┆ 1631311  ┆ 22201230 ┆ … ┆ 0.6       ┆ 0.4       ┆ 0.3       ┆ 0.5       │
│ Patrick   ┆ Baldwin    ┆ 1631116  ┆ 22201230 ┆ … ┆ 0.1       ┆ 0.066667  ┆ 0.666667  ┆ 0.183333  │
│           ┆ Jr.        ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
└───────────┴────────────┴──────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [33]:
# for gameRow in master.iter_rows(named=True):
#     game = gameRow["gameId"]
#     home = gameRow["encodedHomeTeam"]
#     away = gameRow["encodedAwayTeam"]
#     t0 = features.filter((pl.col("gameId") == game) & (pl.col("encodedTeam") == home)).sort(by="numMinutes", descending=True).limit(15)
#     t1 = features.filter((pl.col("gameId") == game) & (pl.col("encodedTeam") == away)).sort(by="numMinutes", descending=True).limit(15)

In [34]:

# Step 1: Join features with master to bring in team info
features_with_team_info = features.join(
    master.select(["gameId", "encodedHomeTeam", "encodedAwayTeam"]),
    on="gameId",
    how="inner"
)

# Step 2: Tag each player as Team 0 or 1
features_tagged = features_with_team_info.with_columns([
    pl.when(pl.col("encodedTeam") == pl.col("encodedHomeTeam")).then(0)
     .when(pl.col("encodedTeam") == pl.col("encodedAwayTeam")).then(1)
     .otherwise(None)
     .alias("teamIndex")
]).filter(pl.col("teamIndex").is_not_null())

# Step 3: Rank by numMinutes within each (gameId, teamIndex)
features_ranked = features_tagged.with_columns([
    pl.col("numMinutes").rank("dense", descending=True)
    .over(["gameId", "teamIndex"])
    .alias("playerRank")
])

# Step 4: Keep top 15 players per team
top_players = features_ranked.filter(pl.col("playerRank") <= 15)

# Step 5: Reshape (melt → pivot → wide format)
stat_cols = [
    "numMinutespg", "pointspg", "assistspg", "blockspg", "stealspg",
    "fieldGoalsAttemptedpg", "fieldGoalsMadepg", "threePointersAttemptedpg",
    "threePointersMadepg", "freeThrowsAttemptedpg", "freeThrowsMadepg",
    "reboundsTotalpg", "turnoverspg",
    "numMinutes", "points", "assists", "blocks", "steals",
    "reboundsTotal", "turnovers"
]

melted = top_players.melt(
    id_vars=["gameId", "teamIndex", "playerRank"],
    value_vars=stat_cols
).with_columns([
    (pl.lit("t") + pl.col("teamIndex").cast(pl.Utf8) +
     pl.lit("_p") + (pl.col("playerRank") - 1).cast(pl.Utf8) +
     pl.lit("_") + pl.col("variable")).alias("column_name")
])

wide = melted.pivot(
    values="value",
    index="gameId",
    columns="column_name",
    aggregate_function="first"
)
# Step 6: Join back to master
master_with_features = master.update(wide, on="gameId")

/var/folders/x3/q9hsrj516xsbqf99gftzt4vr0000gn/T/ipykernel_44775/720648036.py:36: DeprecationWarning: `DataFrame.melt` is deprecated. Use `unpivot` instead, with `index` instead of `id_vars` and `on` instead of `value_vars`
  melted = top_players.melt(
/var/folders/x3/q9hsrj516xsbqf99gftzt4vr0000gn/T/ipykernel_44775/720648036.py:45: DeprecationWarning: The argument `columns` for `DataFrame.pivot` is deprecated. It has been renamed to `on`.
  wide = melted.pivot(

In [35]:
master_with_features

shape: (50_646, 606)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ gameId   ┆ homeScore ┆ awayScore ┆ encodedHo ┆ … ┆ t1_p14_fr ┆ t1_p14_fr ┆ t1_p14_re ┆ t1_p14_tu │
│ ---      ┆ ---       ┆ ---       ┆ meTeam    ┆   ┆ eeThrowsA ┆ eeThrowsM ┆ boundsTot ┆ rnoverspg │
│ i64      ┆ i64       ┆ i64       ┆ ---       ┆   ┆ ttemptedp ┆ adepg     ┆ alpg      ┆ ---       │
│          ┆           ┆           ┆ i64       ┆   ┆ g         ┆ ---       ┆ ---       ┆ f64       │
│          ┆           ┆           ┆           ┆   ┆ ---       ┆ f64       ┆ f64       ┆           │
│          ┆           ┆           ┆           ┆   ┆ f64       ┆           ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 22401193 ┆ 111       ┆ 126       ┆ 11        ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ 22401194 ┆ 132       ┆ 97        ┆ 15        ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ 22401195 ┆ 116       ┆ 105       ┆ 18        ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ 22401196 ┆ 100       ┆ 115       ┆ 20        ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ 22401197 ┆ 125       ┆ 118       ┆ 28        ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ …        ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 28000005 ┆ 85        ┆ 95        ┆ 9         ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ 28000006 ┆ 98        ┆ 99        ┆ 30        ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ 28000007 ┆ 130       ┆ 103       ┆ 2         ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ 28000008 ┆ 96        ┆ 86        ┆ 32        ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ 28000009 ┆ 91        ┆ 110       ┆ 19        ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [36]:
master_with_features

# Assume df is your Polars DataFrame
all_cols = master_with_features.columns

# Split columns into two groups
num_minutes_cols = [col for col in all_cols if col.endswith("numMinutes")]
other_cols = [col for col in all_cols if not col.endswith("numMinutes")]

# Reorder
master_with_features = master_with_features.select(other_cols + num_minutes_cols)
master_with_features

shape: (50_646, 606)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ gameId   ┆ homeScore ┆ awayScore ┆ encodedHo ┆ … ┆ t1_p11_nu ┆ t1_p12_nu ┆ t1_p13_nu ┆ t1_p14_nu │
│ ---      ┆ ---       ┆ ---       ┆ meTeam    ┆   ┆ mMinutes  ┆ mMinutes  ┆ mMinutes  ┆ mMinutes  │
│ i64      ┆ i64       ┆ i64       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│          ┆           ┆           ┆ i64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 22401193 ┆ 111       ┆ 126       ┆ 11        ┆ … ┆ 4.29      ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ 22401194 ┆ 132       ┆ 97        ┆ 15        ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ 22401195 ┆ 116       ┆ 105       ┆ 18        ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ 22401196 ┆ 100       ┆ 115       ┆ 20        ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ 22401197 ┆ 125       ┆ 118       ┆ 28        ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ …        ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 28000005 ┆ 85        ┆ 95        ┆ 9         ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ 28000006 ┆ 98        ┆ 99        ┆ 30        ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ 28000007 ┆ 130       ┆ 103       ┆ 2         ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ 28000008 ┆ 96        ┆ 86        ┆ 32        ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ 28000009 ┆ 91        ┆ 110       ┆ 19        ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [37]:
master_with_features.write_csv("../csv/masterGame.csv")

In [38]:
null_counts = master_with_features.select([
    pl.col(col).is_null().sum().alias(col)
    for col in master_with_features.columns
])
null_counts

shape: (1, 606)
┌────────┬───────────┬───────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ gameId ┆ homeScore ┆ awayScore ┆ encodedHom ┆ … ┆ t1_p11_num ┆ t1_p12_nu ┆ t1_p13_nu ┆ t1_p14_nu │
│ ---    ┆ ---       ┆ ---       ┆ eTeam      ┆   ┆ Minutes    ┆ mMinutes  ┆ mMinutes  ┆ mMinutes  │
│ u32    ┆ u32       ┆ u32       ┆ ---        ┆   ┆ ---        ┆ ---       ┆ ---       ┆ ---       │
│        ┆           ┆           ┆ u32        ┆   ┆ u32        ┆ u32       ┆ u32       ┆ u32       │
╞════════╪═══════════╪═══════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 0      ┆ 0         ┆ 0         ┆ 0          ┆ … ┆ 0          ┆ 0         ┆ 0         ┆ 0         │
└────────┴───────────┴───────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [39]:


player_stats_raw = player_stats_raw.with_columns(
    pl.col("playerteamCity").map_elements(lambda x: mapping_dict.get(x, -1), return_dtype=pl.Int64).alias("encodedTeam")
)

player_stats_raw.write_csv("../csv/PlayerStatistics.csv")