# Data Ingestion EDA

EDA for going from gameview to a pandas dataframe for game simulation.

## Imports

In [8]:
import psycopg2
import pandas as pd
import sqlalchemy
import polars as pl
import numpy as np

## Column work

In [9]:
DATABASE_URL = "postgresql://u7btk4p5c5m73u:p8d8ff8ddeaabbc4fa6652587c63a9944594a63a232b3eba87c457007b20de8c6@cc6sr55p5nfmlu.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com:5432/d6jnenvoupkq12"
engine = sqlalchemy.create_engine(DATABASE_URL)

In [10]:
query = "SELECT * FROM gameview"
raw_df = pd.read_sql_query(query, engine)
raw_df = pl.from_pandas(raw_df)

In [11]:
raw_df.columns

['season',
 'player_id',
 'game_id',
 'team',
 'player',
 'pos',
 'g',
 'mp',
 'personid',
 'gamedate',
 'playerteamcity',
 'playerteamname',
 'opponentteamcity',
 'opponentteamname',
 'gametype',
 'gamelabel',
 'gamesublabel',
 'seriesgamenumber',
 'win',
 'home',
 'numminutes',
 'points',
 'assists',
 'blocks',
 'steals',
 'fieldgoalsattempted',
 'fieldgoalsmade',
 'fieldgoalspercentage',
 'threepointersattempted',
 'threepointersmade',
 'threepointerspercentage',
 'freethrowsattempted',
 'freethrowsmade',
 'freethrowspercentage',
 'reboundsdefensive',
 'reboundsoffensive',
 'reboundstotal',
 'foulspersonal',
 'turnovers',
 'plusminuspoints',
 'per',
 'ts_percent',
 'x3p_ar',
 'f_tr',
 'trb_percent',
 'ast_percent',
 'stl_percent',
 'blk_percent',
 'tov_percent',
 'usg_percent',
 'ows',
 'dws',
 'ws',
 'ws_2',
 'obpm',
 'dbpm',
 'bpm',
 'vorp',
 'fg_per_36_min',
 'fga_per_36_min',
 'p36_fg_percent',
 'x3p_per_36_min',
 'x3pa_per_36_min',
 'p36_x3p_percent',
 'x2p_per_36_min',
 'x2pa_per_36_min',
 'p36_x2p_percent',
 'p36_e_fg_percent',
 'ft_per_36_min',
 'fta_per_36_min',
 'p36_ft_percent',
 'trb_per_36_min',
 'ast_per_36_min',
 'stl_per_36_min',
 'blk_per_36_min',
 'tov_per_36_min',
 'pf_per_36_min',
 'pts_per_36_min',
 'fg_per_100_poss',
 'fga_per_100_poss',
 'p100_fg_percent',
 'x3p_per_100_poss',
 'x3pa_per_100_poss',
 'p100_x3p_percent',
 'x2p_per_100_poss',
 'x2pa_per_100_poss',
 'p100_x2p_percent',
 'p100_e_fg_percent',
 'ft_per_100_poss',
 'fta_per_100_poss',
 'p100_ft_percent',
 'trb_per_100_poss',
 'ast_per_100_poss',
 'stl_per_100_poss',
 'blk_per_100_poss',
 'tov_per_100_poss',
 'pf_per_100_poss',
 'pts_per_100_poss',
 'o_rtg',
 'd_rtg',
 'mp_per_game',
 'fg_per_game',
 'fga_per_game',
 'pg_fg_percent',
 'x3p_per_game',
 'x3pa_per_game',
 'pg_x3p_percent',
 'x2p_per_game',
 'x2pa_per_game',
 'pg_x2p_percent',
 'pg_e_fg_percent',
 'ft_per_game',
 'fta_per_game',
 'pg_ft_percent',
 'trb_per_game',
 'ast_per_game',
 'stl_per_game',
 'blk_per_game',
 'tov_per_game',
 'pf_per_game',
 'pts_per_game',
 'shoot_fg_percent',
 'avg_dist_fga',
 'percent_fga_from_x2p_range',
 'percent_fga_from_x0_3_range',
 'percent_fga_from_x3_10_range',
 'percent_fga_from_x10_16_range',
 'percent_fga_from_x16_3p_range',
 'percent_fga_from_x3p_range',
 'fg_percent_from_x2p_range',
 'fg_percent_from_x0_3_range',
 'fg_percent_from_x3_10_range',
 'fg_percent_from_x10_16_range',
 'fg_percent_from_x16_3p_range',
 'fg_percent_from_x3p_range',
 'percent_assisted_x2p_fg',
 'percent_assisted_x3p_fg',
 'percent_dunks_of_fga',
 'num_of_dunks',
 'percent_corner_3s_of_3pa',
 'corner_3_point_percent',
 'num_heaves_attempted',
 'num_heaves_made']

In [21]:
dropped_cols = ["team", "player", "g", "mp", "gamedate", "playerteamname", "gametype", "gamelabel", "gamesublabel", "seriesgamenumber", "plusminuspoints", "opponentteamname"]
df_drop_cols = raw_df.drop(dropped_cols)
df_drop_cols.shape

(660726, 131)

In [22]:
df_drop_cols.head()

shape: (5, 131)
┌────────┬───────────┬──────────┬─────┬───┬──────────────┬─────────────┬─────────────┬─────────────┐
│ season ┆ player_id ┆ game_id  ┆ pos ┆ … ┆ percent_corn ┆ corner_3_po ┆ num_heaves_ ┆ num_heaves_ │
│ ---    ┆ ---       ┆ ---      ┆ --- ┆   ┆ er_3s_of_3pa ┆ int_percent ┆ attempted   ┆ made        │
│ i64    ┆ str       ┆ i64      ┆ str ┆   ┆ ---          ┆ ---         ┆ ---         ┆ ---         │
│        ┆           ┆          ┆     ┆   ┆ f64          ┆ f64         ┆ i64         ┆ str         │
╞════════╪═══════════╪══════════╪═════╪═══╪══════════════╪═════════════╪═════════════╪═════════════╡
│ 2013   ┆ brookaa01 ┆ 21201042 ┆ PG  ┆ … ┆ 0.143        ┆ 0.0         ┆ 0           ┆ 0           │
│ 2014   ┆ brookaa01 ┆ 21300701 ┆ PG  ┆ … ┆ 0.159        ┆ 0.476       ┆ 3           ┆ 1           │
│ 2014   ┆ brookaa01 ┆ 21300556 ┆ PG  ┆ … ┆ 0.159        ┆ 0.476       ┆ 3           ┆ 1           │
│ 2013   ┆ brookaa01 ┆ 21300141 ┆ PG  ┆ … ┆ 0.143        ┆ 0.0         ┆ 0           ┆ 0           │
│ 2013   ┆ brookaa01 ┆ 21300234 ┆ PG  ┆ … ┆ 0.143        ┆ 0.0         ┆ 0           ┆ 0           │
└────────┴───────────┴──────────┴─────┴───┴──────────────┴─────────────┴─────────────┴─────────────┘

## Cleaning Data

In [23]:
# Get number of null values in each column
null_counts = df_drop_cols.null_count()
null_counts

shape: (1, 131)
┌────────┬───────────┬─────────┬─────┬───┬──────────────┬──────────────┬─────────────┬─────────────┐
│ season ┆ player_id ┆ game_id ┆ pos ┆ … ┆ percent_corn ┆ corner_3_poi ┆ num_heaves_ ┆ num_heaves_ │
│ ---    ┆ ---       ┆ ---     ┆ --- ┆   ┆ er_3s_of_3pa ┆ nt_percent   ┆ attempted   ┆ made        │
│ u32    ┆ u32       ┆ u32     ┆ u32 ┆   ┆ ---          ┆ ---          ┆ ---         ┆ ---         │
│        ┆           ┆         ┆     ┆   ┆ u32          ┆ u32          ┆ u32         ┆ u32         │
╞════════╪═══════════╪═════════╪═════╪═══╪══════════════╪══════════════╪═════════════╪═════════════╡
│ 0      ┆ 0         ┆ 0       ┆ 0   ┆ … ┆ 63701        ┆ 137573       ┆ 0           ┆ 0           │
└────────┴───────────┴─────────┴─────┴───┴──────────────┴──────────────┴─────────────┴─────────────┘

In [24]:
df_fill_null = df_drop_cols.fill_null(0)

In [25]:
# Get number of null values in each column
df_fill_null = df_fill_null.with_columns([pl.col('home').cast(pl.Int64)])
df_fill_null.head()

shape: (5, 131)
┌────────┬───────────┬──────────┬─────┬───┬──────────────┬─────────────┬─────────────┬─────────────┐
│ season ┆ player_id ┆ game_id  ┆ pos ┆ … ┆ percent_corn ┆ corner_3_po ┆ num_heaves_ ┆ num_heaves_ │
│ ---    ┆ ---       ┆ ---      ┆ --- ┆   ┆ er_3s_of_3pa ┆ int_percent ┆ attempted   ┆ made        │
│ i64    ┆ str       ┆ i64      ┆ str ┆   ┆ ---          ┆ ---         ┆ ---         ┆ ---         │
│        ┆           ┆          ┆     ┆   ┆ f64          ┆ f64         ┆ i64         ┆ str         │
╞════════╪═══════════╪══════════╪═════╪═══╪══════════════╪═════════════╪═════════════╪═════════════╡
│ 2013   ┆ brookaa01 ┆ 21201042 ┆ PG  ┆ … ┆ 0.143        ┆ 0.0         ┆ 0           ┆ 0           │
│ 2014   ┆ brookaa01 ┆ 21300701 ┆ PG  ┆ … ┆ 0.159        ┆ 0.476       ┆ 3           ┆ 1           │
│ 2014   ┆ brookaa01 ┆ 21300556 ┆ PG  ┆ … ┆ 0.159        ┆ 0.476       ┆ 3           ┆ 1           │
│ 2013   ┆ brookaa01 ┆ 21300141 ┆ PG  ┆ … ┆ 0.143        ┆ 0.0         ┆ 0           ┆ 0           │
│ 2013   ┆ brookaa01 ┆ 21300234 ┆ PG  ┆ … ┆ 0.143        ┆ 0.0         ┆ 0           ┆ 0           │
└────────┴───────────┴──────────┴─────┴───┴──────────────┴─────────────┴─────────────┴─────────────┘

In [26]:
master = df_fill_null.select([
    "game_id",
    "season",
    "playerteamcity",
    "opponentteamcity"])
# Drop duplicate rows from master_with_features
master = master.unique()
master.shape

(66268, 4)

In [27]:
stat_cols = [
    "personid", "points", "assists", "blocks", "steals", "fieldgoalsattempted", "fieldgoalsmade", "fieldgoalspercentage", "threepointersattempted", "threepointersmade", "threepointerspercentage", "freethrowsattempted", "freethrowsmade", "freethrowspercentage", "reboundsdefensive", "reboundsoffensive", "reboundstotal", "foulspersonal", "turnovers", "per", "ts_percent", "x3p_ar", "f_tr", "trb_percent", "ast_percent", "stl_percent", "blk_percent", "tov_percent", "pg_x3p_percent", "x2p_per_game", "x2pa_per_game", "pg_x2p_percent", "pg_e_fg_percent", "ft_per_game", "fta_per_game", "pg_ft_percent", "trb_per_game", "ast_per_game", "stl_per_game", "blk_per_game", "tov_per_game", "pf_per_game", "pts_per_game", "shoot_fg_percent", "avg_dist_fga", "percent_fga_from_x2p_range", "percent_fga_from_x0_3_range", "percent_fga_from_x3_10_range", "percent_fga_from_x10_16_range", "percent_fga_from_x16_3p_range", "percent_fga_from_x3p_range", "fg_percent_from_x2p_range", "fg_percent_from_x0_3_range", "fg_percent_from_x3_10_range", "fg_percent_from_x10_16_range", "fg_percent_from_x16_3p_range", "fg_percent_from_x3p_range", "percent_assisted_x2p_fg", "percent_assisted_x3p_fg", "percent_dunks_of_fga", "num_of_dunks", "percent_corner_3s_of_3pa", "corner_3_point_percent", "numminutes"
]
for stat in stat_cols:
    for t in ["t0", "t1"]:
        for pNum in range(15):
                col_name = f"{t}_p{pNum}_{stat}"
                master = master.with_columns([
                    pl.lit(0).alias(col_name)
                ])

master.head()

shape: (5, 1_924)
┌──────────┬────────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ game_id  ┆ season ┆ playerteam ┆ opponentte ┆ … ┆ t1_p11_num ┆ t1_p12_nu ┆ t1_p13_nu ┆ t1_p14_nu │
│ ---      ┆ ---    ┆ city       ┆ amcity     ┆   ┆ minutes    ┆ mminutes  ┆ mminutes  ┆ mminutes  │
│ i64      ┆ i64    ┆ ---        ┆ ---        ┆   ┆ ---        ┆ ---       ┆ ---       ┆ ---       │
│          ┆        ┆ str        ┆ str        ┆   ┆ i32        ┆ i32       ┆ i32       ┆ i32       │
╞══════════╪════════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 20200432 ┆ 2002   ┆ Washington ┆ Orlando    ┆ … ┆ 0          ┆ 0         ┆ 0         ┆ 0         │
│ 22000247 ┆ 2021   ┆ Houston    ┆ Dallas     ┆ … ┆ 0          ┆ 0         ┆ 0         ┆ 0         │
│ 20400950 ┆ 2005   ┆ Portland   ┆ Houston    ┆ … ┆ 0          ┆ 0         ┆ 0         ┆ 0         │
│ 22201030 ┆ 2023   ┆ Los        ┆ New        ┆ … ┆ 0          ┆ 0         ┆ 0         ┆ 0         │
│          ┆        ┆ Angeles    ┆ Orleans    ┆   ┆            ┆           ┆           ┆           │
│ 21500368 ┆ 2015   ┆ Minnesota  ┆ Denver     ┆ … ┆ 0          ┆ 0         ┆ 0         ┆ 0         │
└──────────┴────────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [28]:

# Step 3: Rank by numMinutes within each (gameId, teamIndex)
features_ranked = df_fill_null.with_columns([
    pl.col("numminutes").rank("dense", descending=True)
    .over(["game_id", "home"])
    .alias("playerrank")
])

# Step 4: Keep top 15 players per team
top_players = features_ranked.filter(pl.col("playerrank") <= 15)

# Step 5: Reshape (melt → pivot → wide format)
stat_cols = [
    "personid", "numminutes", "points", "assists", "blocks", "steals", "fieldgoalsattempted", "fieldgoalsmade", "fieldgoalspercentage", "threepointersattempted", "threepointersmade", "threepointerspercentage", "freethrowsattempted", "freethrowsmade", "freethrowspercentage", "reboundsdefensive", "reboundsoffensive", "reboundstotal", "foulspersonal", "turnovers", "per", "ts_percent", "x3p_ar", "f_tr", "trb_percent", "ast_percent", "stl_percent", "blk_percent", "tov_percent", "pg_x3p_percent", "x2p_per_game", "x2pa_per_game", "pg_x2p_percent", "pg_e_fg_percent", "ft_per_game", "fta_per_game", "pg_ft_percent", "trb_per_game", "ast_per_game", "stl_per_game", "blk_per_game", "tov_per_game", "pf_per_game", "pts_per_game", "shoot_fg_percent", "avg_dist_fga", "percent_fga_from_x2p_range", "percent_fga_from_x0_3_range", "percent_fga_from_x3_10_range", "percent_fga_from_x10_16_range", "percent_fga_from_x16_3p_range", "percent_fga_from_x3p_range", "fg_percent_from_x2p_range", "fg_percent_from_x0_3_range", "fg_percent_from_x3_10_range", "fg_percent_from_x10_16_range", "fg_percent_from_x16_3p_range", "fg_percent_from_x3p_range", "percent_assisted_x2p_fg", "percent_assisted_x3p_fg", "percent_dunks_of_fga", "num_of_dunks", "percent_corner_3s_of_3pa", "corner_3_point_percent"
]

melted = top_players.melt(
    id_vars=["game_id", "home", "playerrank"],
    value_vars=stat_cols
).with_columns([
    (pl.lit("t") + pl.col("home").cast(pl.Utf8) +
     pl.lit("_p") + (pl.col("playerrank") - 1).cast(pl.Utf8) +
     pl.lit("_") + pl.col("variable")).alias("column_name")
])

wide = melted.pivot(
    values="value",
    index="game_id",
    columns="column_name",
    aggregate_function="first"
)
# Step 6: Join back to master
master_with_features = master.update(wide, on="game_id")
master_with_features.head()

/tmp/ipykernel_8030/3599084429.py:16: DeprecationWarning: `DataFrame.melt` is deprecated; use `DataFrame.unpivot` instead, with `index` instead of `id_vars` and `on` instead of `value_vars`
  melted = top_players.melt(
/tmp/ipykernel_8030/3599084429.py:25: DeprecationWarning: the argument `columns` for `DataFrame.pivot` is deprecated. It was renamed to `on` in version 1.0.0.
  wide = melted.pivot(
/tmp/ipykernel_8030/3599084429.py:25: DeprecationWarning: the argument `columns` for `DataFrame.pivot` is deprecated. It was renamed to `on` in version 1.0.0.
  wide = melted.pivot(

shape: (5, 1_924)
┌──────────┬────────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ game_id  ┆ season ┆ playerteam ┆ opponentte ┆ … ┆ t1_p11_num ┆ t1_p12_nu ┆ t1_p13_nu ┆ t1_p14_nu │
│ ---      ┆ ---    ┆ city       ┆ amcity     ┆   ┆ minutes    ┆ mminutes  ┆ mminutes  ┆ mminutes  │
│ i64      ┆ i64    ┆ ---        ┆ ---        ┆   ┆ ---        ┆ ---       ┆ ---       ┆ ---       │
│          ┆        ┆ str        ┆ str        ┆   ┆ str        ┆ str       ┆ str       ┆ str       │
╞══════════╪════════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 20200432 ┆ 2002   ┆ Washington ┆ Orlando    ┆ … ┆ 0          ┆ 0         ┆ 0         ┆ 0         │
│ 22000247 ┆ 2021   ┆ Houston    ┆ Dallas     ┆ … ┆ 0          ┆ 0         ┆ 0         ┆ 0         │
│ 20400950 ┆ 2005   ┆ Portland   ┆ Houston    ┆ … ┆ 0          ┆ 0         ┆ 0         ┆ 0         │
│ 22201030 ┆ 2023   ┆ Los        ┆ New        ┆ … ┆ 0          ┆ 0         ┆ 0         ┆ 0         │
│          ┆        ┆ Angeles    ┆ Orleans    ┆   ┆            ┆           ┆           ┆           │
│ 21500368 ┆ 2015   ┆ Minnesota  ┆ Denver     ┆ … ┆ 0          ┆ 0         ┆ 0         ┆ 0         │
└──────────┴────────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [29]:
# Cast all columns except the first 4 to float
float_cols = master_with_features.columns[4:]
master_with_features = master_with_features.with_columns([pl.col(col).cast(pl.Float64) for col in float_cols])
master_with_features.head()

shape: (5, 1_924)
┌──────────┬────────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ game_id  ┆ season ┆ playerteam ┆ opponentte ┆ … ┆ t1_p11_num ┆ t1_p12_nu ┆ t1_p13_nu ┆ t1_p14_nu │
│ ---      ┆ ---    ┆ city       ┆ amcity     ┆   ┆ minutes    ┆ mminutes  ┆ mminutes  ┆ mminutes  │
│ i64      ┆ i64    ┆ ---        ┆ ---        ┆   ┆ ---        ┆ ---       ┆ ---       ┆ ---       │
│          ┆        ┆ str        ┆ str        ┆   ┆ f64        ┆ f64       ┆ f64       ┆ f64       │
╞══════════╪════════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 20200432 ┆ 2002   ┆ Washington ┆ Orlando    ┆ … ┆ 0.0        ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ 22000247 ┆ 2021   ┆ Houston    ┆ Dallas     ┆ … ┆ 0.0        ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ 20400950 ┆ 2005   ┆ Portland   ┆ Houston    ┆ … ┆ 0.0        ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ 22201030 ┆ 2023   ┆ Los        ┆ New        ┆ … ┆ 0.0        ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│          ┆        ┆ Angeles    ┆ Orleans    ┆   ┆            ┆           ┆           ┆           │
│ 21500368 ┆ 2015   ┆ Minnesota  ┆ Denver     ┆ … ┆ 0.0        ┆ 0.0       ┆ 0.0       ┆ 0.0       │
└──────────┴────────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [30]:
master_with_features = master_with_features.filter((pl.col('t0_p0_numminutes') != 0) & (pl.col('t1_p0_numminutes') != 0))
master_with_features.shape

(57340, 1924)

In [31]:
master_with_features.write_csv("../csv/data.csv")

In [32]:
# Drop rows where t0_p0_numminutes or t1_p0_numminutes == 0
master_with_features = master_with_features.filter((pl.col('t0_p0_numminutes') != 0) & (pl.col('t1_p0_numminutes') != 0))
master_with_features.head()

shape: (5, 1_924)
┌──────────┬────────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ game_id  ┆ season ┆ playerteam ┆ opponentte ┆ … ┆ t1_p11_num ┆ t1_p12_nu ┆ t1_p13_nu ┆ t1_p14_nu │
│ ---      ┆ ---    ┆ city       ┆ amcity     ┆   ┆ minutes    ┆ mminutes  ┆ mminutes  ┆ mminutes  │
│ i64      ┆ i64    ┆ ---        ┆ ---        ┆   ┆ ---        ┆ ---       ┆ ---       ┆ ---       │
│          ┆        ┆ str        ┆ str        ┆   ┆ f64        ┆ f64       ┆ f64       ┆ f64       │
╞══════════╪════════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 20200432 ┆ 2002   ┆ Washington ┆ Orlando    ┆ … ┆ 0.0        ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ 22000247 ┆ 2021   ┆ Houston    ┆ Dallas     ┆ … ┆ 0.0        ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ 20400950 ┆ 2005   ┆ Portland   ┆ Houston    ┆ … ┆ 0.0        ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ 22201030 ┆ 2023   ┆ Los        ┆ New        ┆ … ┆ 0.0        ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│          ┆        ┆ Angeles    ┆ Orleans    ┆   ┆            ┆           ┆           ┆           │
│ 21500368 ┆ 2015   ┆ Minnesota  ┆ Denver     ┆ … ┆ 0.0        ┆ 0.0       ┆ 0.0       ┆ 0.0       │
└──────────┴────────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘