# Data Ingestion EDA

EDA for going from gameview to a pandas dataframe for game simulation.

## Imports

In [26]:
import psycopg2
import pandas as pd
import sqlalchemy
import polars as pl
import numpy as np

## Column work

In [27]:
DATABASE_URL = "postgresql://u7btk4p5c5m73u:p8d8ff8ddeaabbc4fa6652587c63a9944594a63a232b3eba87c457007b20de8c6@cc6sr55p5nfmlu.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com:5432/d6jnenvoupkq12"
engine = sqlalchemy.create_engine(DATABASE_URL)

In [28]:
query = "SELECT * FROM gameview"
raw_df = pd.read_sql_query(query, engine)
raw_df = pl.from_pandas(raw_df)

In [57]:
raw_df.head()

shape: (5, 143)
┌────────┬───────────┬──────────┬──────┬───┬─────────────┬─────────────┬─────────────┬─────────────┐
│ season ┆ player_id ┆ game_id  ┆ team ┆ … ┆ percent_cor ┆ corner_3_po ┆ num_heaves_ ┆ num_heaves_ │
│ ---    ┆ ---       ┆ ---      ┆ ---  ┆   ┆ ner_3s_of_3 ┆ int_percent ┆ attempted   ┆ made        │
│ i64    ┆ str       ┆ i64      ┆ str  ┆   ┆ pa          ┆ ---         ┆ ---         ┆ ---         │
│        ┆           ┆          ┆      ┆   ┆ ---         ┆ f64         ┆ i64         ┆ str         │
│        ┆           ┆          ┆      ┆   ┆ f64         ┆             ┆             ┆             │
╞════════╪═══════════╪══════════╪══════╪═══╪═════════════╪═════════════╪═════════════╪═════════════╡
│ 2013   ┆ brookaa01 ┆ 21201042 ┆ HOU  ┆ … ┆ 0.143       ┆ 0.0         ┆ 0           ┆ 0           │
│ 2014   ┆ brookaa01 ┆ 21300701 ┆ HOU  ┆ … ┆ 0.159       ┆ 0.476       ┆ 3           ┆ 1           │
│ 2014   ┆ brookaa01 ┆ 21300556 ┆ HOU  ┆ … ┆ 0.159       ┆ 0.476       ┆ 3           ┆ 1           │
│ 2013   ┆ brookaa01 ┆ 21300141 ┆ HOU  ┆ … ┆ 0.143       ┆ 0.0         ┆ 0           ┆ 0           │
│ 2013   ┆ brookaa01 ┆ 21300234 ┆ HOU  ┆ … ┆ 0.143       ┆ 0.0         ┆ 0           ┆ 0           │
└────────┴───────────┴──────────┴──────┴───┴─────────────┴─────────────┴─────────────┴─────────────┘

In [58]:
dropped_cols = ["team", "player", "g", "mp", "gamedate", "playerteamname", "gametype", "gamelabel", "gamesublabel", "seriesgamenumber", "plusminuspoints", "opponentteamname"]
df_drop_cols = raw_df.drop(dropped_cols)
df_drop_cols.shape

(660726, 131)

In [59]:
df_drop_cols.head()

shape: (5, 131)
┌────────┬───────────┬──────────┬─────┬───┬──────────────┬─────────────┬─────────────┬─────────────┐
│ season ┆ player_id ┆ game_id  ┆ pos ┆ … ┆ percent_corn ┆ corner_3_po ┆ num_heaves_ ┆ num_heaves_ │
│ ---    ┆ ---       ┆ ---      ┆ --- ┆   ┆ er_3s_of_3pa ┆ int_percent ┆ attempted   ┆ made        │
│ i64    ┆ str       ┆ i64      ┆ str ┆   ┆ ---          ┆ ---         ┆ ---         ┆ ---         │
│        ┆           ┆          ┆     ┆   ┆ f64          ┆ f64         ┆ i64         ┆ str         │
╞════════╪═══════════╪══════════╪═════╪═══╪══════════════╪═════════════╪═════════════╪═════════════╡
│ 2013   ┆ brookaa01 ┆ 21201042 ┆ PG  ┆ … ┆ 0.143        ┆ 0.0         ┆ 0           ┆ 0           │
│ 2014   ┆ brookaa01 ┆ 21300701 ┆ PG  ┆ … ┆ 0.159        ┆ 0.476       ┆ 3           ┆ 1           │
│ 2014   ┆ brookaa01 ┆ 21300556 ┆ PG  ┆ … ┆ 0.159        ┆ 0.476       ┆ 3           ┆ 1           │
│ 2013   ┆ brookaa01 ┆ 21300141 ┆ PG  ┆ … ┆ 0.143        ┆ 0.0         ┆ 0           ┆ 0           │
│ 2013   ┆ brookaa01 ┆ 21300234 ┆ PG  ┆ … ┆ 0.143        ┆ 0.0         ┆ 0           ┆ 0           │
└────────┴───────────┴──────────┴─────┴───┴──────────────┴─────────────┴─────────────┴─────────────┘

## Cleaning Data

In [60]:
# Get number of null values in each column
null_counts = df_drop_cols.null_count()
null_counts

shape: (1, 131)
┌────────┬───────────┬─────────┬─────┬───┬──────────────┬──────────────┬─────────────┬─────────────┐
│ season ┆ player_id ┆ game_id ┆ pos ┆ … ┆ percent_corn ┆ corner_3_poi ┆ num_heaves_ ┆ num_heaves_ │
│ ---    ┆ ---       ┆ ---     ┆ --- ┆   ┆ er_3s_of_3pa ┆ nt_percent   ┆ attempted   ┆ made        │
│ u32    ┆ u32       ┆ u32     ┆ u32 ┆   ┆ ---          ┆ ---          ┆ ---         ┆ ---         │
│        ┆           ┆         ┆     ┆   ┆ u32          ┆ u32          ┆ u32         ┆ u32         │
╞════════╪═══════════╪═════════╪═════╪═══╪══════════════╪══════════════╪═════════════╪═════════════╡
│ 0      ┆ 0         ┆ 0       ┆ 0   ┆ … ┆ 63701        ┆ 137573       ┆ 0           ┆ 0           │
└────────┴───────────┴─────────┴─────┴───┴──────────────┴──────────────┴─────────────┴─────────────┘

In [67]:
df_fill_null = df_drop_cols.fill_null(0)

In [68]:
# Get number of null values in each column
df_fill_null = df_fill_null.with_columns([pl.col('home').cast(pl.Int64)])
df_fill_null.head()

shape: (5, 131)
┌────────┬───────────┬──────────┬─────┬───┬──────────────┬─────────────┬─────────────┬─────────────┐
│ season ┆ player_id ┆ game_id  ┆ pos ┆ … ┆ percent_corn ┆ corner_3_po ┆ num_heaves_ ┆ num_heaves_ │
│ ---    ┆ ---       ┆ ---      ┆ --- ┆   ┆ er_3s_of_3pa ┆ int_percent ┆ attempted   ┆ made        │
│ i64    ┆ str       ┆ i64      ┆ str ┆   ┆ ---          ┆ ---         ┆ ---         ┆ ---         │
│        ┆           ┆          ┆     ┆   ┆ f64          ┆ f64         ┆ i64         ┆ str         │
╞════════╪═══════════╪══════════╪═════╪═══╪══════════════╪═════════════╪═════════════╪═════════════╡
│ 2013   ┆ brookaa01 ┆ 21201042 ┆ PG  ┆ … ┆ 0.143        ┆ 0.0         ┆ 0           ┆ 0           │
│ 2014   ┆ brookaa01 ┆ 21300701 ┆ PG  ┆ … ┆ 0.159        ┆ 0.476       ┆ 3           ┆ 1           │
│ 2014   ┆ brookaa01 ┆ 21300556 ┆ PG  ┆ … ┆ 0.159        ┆ 0.476       ┆ 3           ┆ 1           │
│ 2013   ┆ brookaa01 ┆ 21300141 ┆ PG  ┆ … ┆ 0.143        ┆ 0.0         ┆ 0           ┆ 0           │
│ 2013   ┆ brookaa01 ┆ 21300234 ┆ PG  ┆ … ┆ 0.143        ┆ 0.0         ┆ 0           ┆ 0           │
└────────┴───────────┴──────────┴─────┴───┴──────────────┴─────────────┴─────────────┴─────────────┘

In [73]:
master = df_fill_null.select([
    "game_id",
    "season",
    "playerteamcity",
    "opponentteamcity"])
# Drop duplicate rows from master_with_features
master = master.unique()
master.shape

(66268, 4)

In [74]:
stat_cols = [
    "numminutes", "points", "assists", "blocks", "steals", "fieldgoalsattempted", "fieldgoalsmade", "fieldgoalspercentage", "threepointersattempted", "threepointersmade", "threepointerspercentage", "freethrowsattempted", "freethrowsmade", "freethrowspercentage", "reboundsdefensive", "reboundsoffensive", "reboundstotal", "foulspersonal", "turnovers", "per", "ts_percent", "x3p_ar", "f_tr", "trb_percent", "ast_percent", "stl_percent", "blk_percent", "tov_percent", "pg_x3p_percent", "x2p_per_game", "x2pa_per_game", "pg_x2p_percent", "pg_e_fg_percent", "ft_per_game", "fta_per_game", "pg_ft_percent", "trb_per_game", "ast_per_game", "stl_per_game", "blk_per_game", "tov_per_game", "pf_per_game", "pts_per_game", "shoot_fg_percent", "avg_dist_fga", "percent_fga_from_x2p_range", "percent_fga_from_x0_3_range", "percent_fga_from_x3_10_range", "percent_fga_from_x10_16_range", "percent_fga_from_x16_3p_range", "percent_fga_from_x3p_range", "fg_percent_from_x2p_range", "fg_percent_from_x0_3_range", "fg_percent_from_x3_10_range", "fg_percent_from_x10_16_range", "fg_percent_from_x16_3p_range", "fg_percent_from_x3p_range", "percent_assisted_x2p_fg", "percent_assisted_x3p_fg", "percent_dunks_of_fga", "num_of_dunks", "percent_corner_3s_of_3pa", "corner_3_point_percent"
]
for stat in stat_cols:
    for t in ["t0", "t1"]:
        for pNum in range(15):
                col_name = f"{t}_p{pNum}_{stat}"
                master = master.with_columns([
                    pl.lit(0).alias(col_name)
                ])

master.head()

shape: (5, 1_894)
┌──────────┬────────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ game_id  ┆ season ┆ playerteam ┆ opponentte ┆ … ┆ t1_p11_cor ┆ t1_p12_co ┆ t1_p13_co ┆ t1_p14_co │
│ ---      ┆ ---    ┆ city       ┆ amcity     ┆   ┆ ner_3_poin ┆ rner_3_po ┆ rner_3_po ┆ rner_3_po │
│ i64      ┆ i64    ┆ ---        ┆ ---        ┆   ┆ t_percent  ┆ int_perce ┆ int_perce ┆ int_perce │
│          ┆        ┆ str        ┆ str        ┆   ┆ ---        ┆ nt        ┆ nt        ┆ nt        │
│          ┆        ┆            ┆            ┆   ┆ i32        ┆ ---       ┆ ---       ┆ ---       │
│          ┆        ┆            ┆            ┆   ┆            ┆ i32       ┆ i32       ┆ i32       │
╞══════════╪════════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 21700988 ┆ 2018   ┆ Washington ┆ Miami      ┆ … ┆ 0          ┆ 0         ┆ 0         ┆ 0         │
│ 41500401 ┆ 2016   ┆ Cleveland  ┆ Golden     ┆ … ┆ 0          ┆ 0         ┆ 0         ┆ 0         │
│          ┆        ┆            ┆ State      ┆   ┆            ┆           ┆           ┆           │
│ 21000701 ┆ 2011   ┆ Miami      ┆ Oklahoma   ┆ … ┆ 0          ┆ 0         ┆ 0         ┆ 0         │
│          ┆        ┆            ┆ City       ┆   ┆            ┆           ┆           ┆           │
│ 22400977 ┆ 2025   ┆ Los        ┆ Phoenix    ┆ … ┆ 0          ┆ 0         ┆ 0         ┆ 0         │
│          ┆        ┆ Angeles    ┆            ┆   ┆            ┆           ┆           ┆           │
│ 11900028 ┆ 2019   ┆ Chicago    ┆ New        ┆ … ┆ 0          ┆ 0         ┆ 0         ┆ 0         │
│          ┆        ┆            ┆ Orleans    ┆   ┆            ┆           ┆           ┆           │
└──────────┴────────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [76]:

# Step 3: Rank by numMinutes within each (gameId, teamIndex)
features_ranked = df_fill_null.with_columns([
    pl.col("numminutes").rank("dense", descending=True)
    .over(["game_id", "home"])
    .alias("playerrank")
])

# Step 4: Keep top 15 players per team
top_players = features_ranked.filter(pl.col("playerrank") <= 15)

# Step 5: Reshape (melt → pivot → wide format)
stat_cols = [
    "numminutes", "points", "assists", "blocks", "steals", "fieldgoalsattempted", "fieldgoalsmade", "fieldgoalspercentage", "threepointersattempted", "threepointersmade", "threepointerspercentage", "freethrowsattempted", "freethrowsmade", "freethrowspercentage", "reboundsdefensive", "reboundsoffensive", "reboundstotal", "foulspersonal", "turnovers", "per", "ts_percent", "x3p_ar", "f_tr", "trb_percent", "ast_percent", "stl_percent", "blk_percent", "tov_percent", "pg_x3p_percent", "x2p_per_game", "x2pa_per_game", "pg_x2p_percent", "pg_e_fg_percent", "ft_per_game", "fta_per_game", "pg_ft_percent", "trb_per_game", "ast_per_game", "stl_per_game", "blk_per_game", "tov_per_game", "pf_per_game", "pts_per_game", "shoot_fg_percent", "avg_dist_fga", "percent_fga_from_x2p_range", "percent_fga_from_x0_3_range", "percent_fga_from_x3_10_range", "percent_fga_from_x10_16_range", "percent_fga_from_x16_3p_range", "percent_fga_from_x3p_range", "fg_percent_from_x2p_range", "fg_percent_from_x0_3_range", "fg_percent_from_x3_10_range", "fg_percent_from_x10_16_range", "fg_percent_from_x16_3p_range", "fg_percent_from_x3p_range", "percent_assisted_x2p_fg", "percent_assisted_x3p_fg", "percent_dunks_of_fga", "num_of_dunks", "percent_corner_3s_of_3pa", "corner_3_point_percent"
]

melted = top_players.melt(
    id_vars=["game_id", "home", "playerrank"],
    value_vars=stat_cols
).with_columns([
    (pl.lit("t") + pl.col("home").cast(pl.Utf8) +
     pl.lit("_p") + (pl.col("playerrank") - 1).cast(pl.Utf8) +
     pl.lit("_") + pl.col("variable")).alias("column_name")
])

wide = melted.pivot(
    values="value",
    index="game_id",
    columns="column_name",
    aggregate_function="first"
)
# Step 6: Join back to master
master_with_features = master.update(wide, on="game_id")
master_with_features.head()

/tmp/ipykernel_24589/1600483289.py:16: DeprecationWarning: `DataFrame.melt` is deprecated; use `DataFrame.unpivot` instead, with `index` instead of `id_vars` and `on` instead of `value_vars`
  melted = top_players.melt(
/tmp/ipykernel_24589/1600483289.py:25: DeprecationWarning: the argument `columns` for `DataFrame.pivot` is deprecated. It was renamed to `on` in version 1.0.0.
  wide = melted.pivot(

shape: (5, 1_894)
┌──────────┬────────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ game_id  ┆ season ┆ playerteam ┆ opponentte ┆ … ┆ t1_p11_cor ┆ t1_p12_co ┆ t1_p13_co ┆ t1_p14_co │
│ ---      ┆ ---    ┆ city       ┆ amcity     ┆   ┆ ner_3_poin ┆ rner_3_po ┆ rner_3_po ┆ rner_3_po │
│ i64      ┆ i64    ┆ ---        ┆ ---        ┆   ┆ t_percent  ┆ int_perce ┆ int_perce ┆ int_perce │
│          ┆        ┆ str        ┆ str        ┆   ┆ ---        ┆ nt        ┆ nt        ┆ nt        │
│          ┆        ┆            ┆            ┆   ┆ str        ┆ ---       ┆ ---       ┆ ---       │
│          ┆        ┆            ┆            ┆   ┆            ┆ str       ┆ str       ┆ str       │
╞══════════╪════════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 21700988 ┆ 2018   ┆ Washington ┆ Miami      ┆ … ┆ 0          ┆ 0         ┆ 0         ┆ 0         │
│ 41500401 ┆ 2016   ┆ Cleveland  ┆ Golden     ┆ … ┆ 0          ┆ 0         ┆ 0         ┆ 0         │
│          ┆        ┆            ┆ State      ┆   ┆            ┆           ┆           ┆           │
│ 21000701 ┆ 2011   ┆ Miami      ┆ Oklahoma   ┆ … ┆ 0          ┆ 0         ┆ 0         ┆ 0         │
│          ┆        ┆            ┆ City       ┆   ┆            ┆           ┆           ┆           │
│ 22400977 ┆ 2025   ┆ Los        ┆ Phoenix    ┆ … ┆ 0          ┆ 0         ┆ 0         ┆ 0         │
│          ┆        ┆ Angeles    ┆            ┆   ┆            ┆           ┆           ┆           │
│ 11900028 ┆ 2019   ┆ Chicago    ┆ New        ┆ … ┆ 0          ┆ 0         ┆ 0         ┆ 0         │
│          ┆        ┆            ┆ Orleans    ┆   ┆            ┆           ┆           ┆           │
└──────────┴────────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [80]:
# Get number of rows where t0_p0_numminutes == 0
num_zero_minutes = master_with_features.filter(pl.col('t0_p0_numminutes') == 0).height
num_zero_minutes

ComputeError: cannot compare string with numeric type (i32)

In [65]:
import itertools
from tqdm import tqdm

# Step 1: For each game and team, get top 15 players ordered by minutes
grouped = top_players.groupby(['gameId', 'teamIndex'])
permuted_rows = []
for (gameId, teamIndex), group in tqdm(grouped):
    players = group.sort('numminutes', reverse=True).to_dicts()
    # Generate all permutations of player orderings
    for perm in itertools.permutations(players, len(players)):
        row = {'gameId': gameId, 'teamIndex': teamIndex}
        for i, player in enumerate(perm):
            for stat in stat_cols:
                col_name = f't{teamIndex}_p{i}_{stat}'
                row[col_name] = player.get(stat, None)
        permuted_rows.append(row)

# Step 2: Create DataFrame from permuted rows
permuted_df = pl.DataFrame(permuted_rows)
permuted_df.head()

AttributeError: 'DataFrame' object has no attribute 'groupby'